/* Catalogue: luxury watches from Titan's own luxury lines (Nebula, Xylys, Edge,
 * Stellar, Maritime) and the luxury brands sold on Tata CLiQ Luxury
 * (Rado, Longines, Tissot, Frederique Constant, Movado, Hugo Boss, Coach, ...).
 *
 * Prices are in ₹ (India), collected Oct 2026 from brand sites and authorised
 * retailers. Where only a collection price range was available, the price is a
 * typical model in that range. p = price shown, mrp = crossed-out MRP (set it
 * equal to p when there is no discount).
 *
 * Variant helper V(name, dial, case, strap, accent, swatch)
 * Each colour is a token from TOKENS below or a #hex value.
 */
const TOKENS = {
  black: '#151515', jet: '#0b0b0b', white: '#f4f3ef', silver: '#dcdde0', blue: '#1d4f8c', navy: '#15213b',
  green: '#1f4d3a', olive: '#4b5a2e', gold: '#d4af37', rose: '#d9937f', champagne: '#ecd9aa', brown: '#6b4226',
  tan: '#a8703d', red: '#a3161f', grey: '#5a5d63', pink: '#f4b6c2', purple: '#7d6bd6', teal: '#0f6e6e',
  orange: '#ff6b1a', cream: '#f1e8d2', steel: '#c9ccd1', gun: '#4a4d52', sky: '#8ccdf5',
  choc: '#3d2a1e', ivory: '#fbf7ec', lavender: '#c8b8f0', beige: '#d9c7a3', wine: '#6d1a2a', dgreen: '#123a2c',
  ceramic: '#1a1a1c', yg: '#d9b44a', pg: '#e0a487', mop: '#f3eee8', ice: '#bfe3f2',
};
const t = (c) => (c && c[0] !== '#' ? TOKENS[c] || c : c);
function V(name, dial, kase, strap, accent, swatch) {
  return { name, dial: t(dial), case: t(kase), strap: t(strap), accent: t(accent || '#e03131'), swatch: t(swatch || dial) };
}

// s (style): dress | field | diver | chrono      sq: true = square case
// st (strap): leather | metal | jubilee | mesh | rubber | fabric
// dn = text printed on the dial (defaults to the brand name)
// women: true = listed under "For Her"
module.exports = [
  // ================= TITAN NEBULA (18k solid gold) =================
  { b: 'Titan', dn: 'NEBULA', m: 'Nebula Vintage Studded Indices', ref: 'NU600DL22', cat: 'nebula', s: 'dress', p: 180000, mrp: 180000, st: 'leather', size: '38 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 8, ind: 'dots',
    blurb: "Nebula is India's first solid gold watch brand, from Titan. This vintage-style piece has an 18 karat solid gold case and studded indices.",
    feats: ['18 karat solid gold case', 'Studded hour markers', 'Sapphire crystal', 'Genuine leather strap', 'Certificate of gold purity'],
    v: [V('White / Brown', 'ivory', 'yg', 'brown', '#3a2a05', '#6b4226'), V('Champagne / Black', 'champagne', 'yg', 'black', '#3a2a05', '#151515')] },
  { b: 'Titan', dn: 'NEBULA', m: 'Nebula Vintage 18k Gold Leather', ref: 'NU1045DL02', cat: 'nebula', s: 'dress', p: 290000, mrp: 290000, st: 'leather', size: '40 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 7, ind: 'roman',
    blurb: 'A classic white dial in a solid 18k gold case - timeless Nebula craftsmanship for weddings and celebrations.',
    feats: ['18 karat solid gold case', 'Roman numeral dial', 'Sapphire crystal', 'Genuine leather strap'],
    v: [V('White Dial', 'white', 'yg', 'brown', '#3a2a05', '#f4f3ef'), V('Black Dial', 'black', 'yg', 'black', '#d9b44a', '#151515')] },
  { b: 'Titan', dn: 'NEBULA', m: 'Nebula Swiss Automatic 18k Gold', ref: '5042GL01', cat: 'nebula', s: 'dress', p: 325000, mrp: 325000, st: 'leather', size: '41 mm', wr: '50m', mv: 'Swiss Automatic', glass: 'Sapphire Crystal', pop: 8, ind: 'stick', auto: true, date: true,
    blurb: 'Solid 18k gold meets a Swiss automatic movement - the Nebula Automatic is one of the finest watches made by Titan.',
    feats: ['Swiss automatic movement', '18 karat solid gold case', 'Exhibition case back', 'Sapphire crystal', 'Date window'],
    v: [V('White Dial', 'white', 'yg', 'brown', '#3a2a05', '#f4f3ef'), V('Blue Dial', 'blue', 'yg', 'navy', '#d9b44a', '#1d4f8c')] },
  { b: 'Titan', dn: 'NEBULA', m: 'Nebula Lustre 18k Gold', ref: '', cat: 'nebula', s: 'dress', p: 350000, mrp: 350000, st: 'leather', size: '40 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 6, ind: 'stick',
    blurb: 'Nebula Lustre - a glowing textured dial framed by a polished 18k gold case.',
    feats: ['18 karat solid gold case', 'Textured dial', 'Sapphire crystal', 'Leather strap'],
    v: [V('Champagne', 'champagne', 'yg', 'brown', '#3a2a05', '#ecd9aa'), V('Silver', 'silver', 'yg', 'black', '#1d1d1f', '#dcdde0')] },
  { b: 'Titan', dn: 'NEBULA', m: 'Nebula Deccan Treasures Diamond', ref: '5065DL02', cat: 'nebula', s: 'dress', p: 596000, mrp: 596000, st: 'leather', size: '41 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 7, ind: 'dots', date: true,
    blurb: 'Inspired by the royal Deccan, this Nebula has diamond-studded indices on a deep blue dial in solid 18k gold.',
    feats: ['18 karat solid gold case', 'Diamond-studded indices', 'Date window', 'Sapphire crystal'],
    v: [V('Royal Blue', 'navy', 'yg', 'navy', '#d9b44a', '#15213b')] },
  { b: 'Titan', dn: 'NEBULA', m: 'Nebula Vintage Diamond Bezel', ref: '5033DM02', cat: 'nebula', s: 'dress', p: 750000, mrp: 750000, st: 'jubilee', size: '38 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 6, ind: 'roman', fluted: true,
    blurb: 'A showpiece of Indian watchmaking - diamond-studded bezel and a solid 18k gold bracelet.',
    feats: ['18 karat solid gold case & bracelet', 'Diamond-studded bezel', 'Sapphire crystal', 'Certificate of authenticity'],
    v: [V('Gold Dial', 'champagne', 'yg', 'yg', '#3a2a05', '#d9b44a')] },
  { b: 'Titan', dn: 'NEBULA', m: 'Nebula Rice Grain Gold Bracelet', ref: '5069DM01', cat: 'nebula', s: 'dress', p: 1213000, mrp: 1213000, st: 'jubilee', size: '38 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 6, ind: 'stick',
    blurb: 'The most exclusive Nebula - a heavy, hand-finished "rice grain" bracelet in solid 18k gold.',
    feats: ['Solid 18k gold rice-grain bracelet', 'Hand-finished', 'Sapphire crystal', 'Collector piece'],
    v: [V('Gold', 'champagne', 'yg', 'yg', '#3a2a05', '#d9b44a')] },
  { b: 'Titan', dn: 'NEBULA', m: 'Nebula Ashvi Pink Gold Women', ref: '', cat: 'nebula', s: 'dress', p: 436000, mrp: 436000, st: 'jubilee', size: '26 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 7, small: true, ind: 'dots', women: true,
    blurb: 'Nebula Ashvi - an 18k solid pink gold bracelet watch set with diamonds and rubies. Jewellery first, watch second.',
    feats: ['18k solid pink gold', 'Diamonds and rubies', 'Bracelet design', 'Sapphire crystal'],
    v: [V('Pink Gold', 'mop', 'pg', 'pg', '#a3161f', '#e0a487')] },
  { b: 'Titan', dn: 'NEBULA', m: 'Nebula Kalagya Women', ref: '', cat: 'nebula', s: 'dress', p: 245000, mrp: 245000, st: 'jubilee', size: '24 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 6, small: true, ind: 'dots', women: true,
    blurb: 'Kalagya by Nebula celebrates Indian craft traditions in solid 18 karat gold, designed for her. (Approx. price)',
    feats: ['18 karat solid gold', 'Traditional Indian motifs', 'Sapphire crystal'],
    v: [V('Yellow Gold', 'ivory', 'yg', 'yg', '#3a2a05', '#d9b44a'), V('Pink Gold', 'mop', 'pg', 'pg', '#6b3a2e', '#e0a487')] },

  // ================= XYLYS (Swiss made by Titan) =================
  { b: 'Xylys', m: 'Swiss Analog Silver Dial', ref: '40037KM01E', cat: 'xylys', s: 'dress', p: 17850, mrp: 25500, st: 'metal', size: '40 mm', wr: '50m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 8, ind: 'stick', date: true,
    blurb: "Xylys is Titan's Swiss-made brand - Swiss precision with clean, modern design at an accessible price.",
    feats: ['Swiss made', 'Sapphire crystal', 'Date window', 'Stainless steel bracelet'],
    v: [V('Silver Dial', 'silver', 'steel', 'steel', '#1d1d1f', '#dcdde0'), V('Blue Dial', 'blue', 'steel', 'steel', '#ffffff')] },
  { b: 'Xylys', m: 'Integra Swiss Analog', ref: '', cat: 'xylys', s: 'dress', p: 26910, mrp: 29900, st: 'metal', size: '41 mm', wr: '100m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 8, ind: 'stick', date: true,
    blurb: 'Xylys Integra - a sporty-luxe integrated bracelet design with a textured dial.',
    feats: ['Integrated bracelet design', 'Swiss made', 'Sapphire crystal', '100m water resistance'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Green', 'green', 'steel', 'steel', '#ffffff'), V('Grey', 'grey', 'steel', 'steel', '#ffffff')] },
  { b: 'Xylys', m: 'Ceramic Analog Date', ref: '', cat: 'xylys', s: 'dress', p: 23450, mrp: 33500, st: 'metal', size: '40 mm', wr: '50m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 7, ind: 'stick', date: true,
    blurb: 'Scratch-resistant high-tech ceramic with a deep, glossy finish - light, modern and luxurious.',
    feats: ['High-tech ceramic case & bracelet', 'Swiss made', 'Sapphire crystal', 'Date window'],
    v: [V('Black Ceramic', 'black', 'ceramic', 'ceramic', '#c9ccd1', '#1a1a1c'), V('Blue Ceramic', 'navy', '#1e2f5c', '#1e2f5c', '#ffffff', '#1e2f5c')] },
  { b: 'Xylys', m: 'Titanium Chronograph', ref: '', cat: 'xylys', s: 'chrono', p: 32550, mrp: 46500, st: 'metal', size: '43 mm', wr: '100m', mv: 'Swiss Chronograph Quartz', glass: 'Sapphire Crystal', pop: 7, ind: 'stick', date: true,
    blurb: 'A lightweight titanium chronograph from Xylys - sporty, strong and Swiss made.',
    feats: ['Titanium case & bracelet', 'Chronograph', 'Sapphire crystal', '100m water resistance'],
    v: [V('Black Dial', 'black', '#a9abae', '#a9abae', '#ff6b1a', '#151515'), V('Blue Dial', 'navy', '#a9abae', '#a9abae', '#ffffff', '#15213b')] },
  { b: 'Xylys', m: 'Swiss Multifunction', ref: '', cat: 'xylys', s: 'chrono', p: 22050, mrp: 31500, st: 'leather', size: '42 mm', wr: '50m', mv: 'Swiss Quartz Multifunction', glass: 'Sapphire Crystal', pop: 6, ind: 'stick',
    blurb: 'Day, date and 24-hour sub-dials on a rich leather strap - a classic Swiss multifunction.',
    feats: ['Day, date & 24-hour sub-dials', 'Swiss made', 'Sapphire crystal', 'Leather strap'],
    v: [V('Blue / Brown', 'blue', 'steel', 'brown', '#ffffff', '#1d4f8c'), V('Black / Black', 'black', 'rose', 'black', '#d9937f')] },
  { b: 'Xylys', m: 'Swiss Automatic Open Heart', ref: '', cat: 'xylys', s: 'dress', p: 58500, mrp: 58500, st: 'leather', size: '42 mm', wr: '50m', mv: 'Swiss Automatic', glass: 'Sapphire Crystal', pop: 7, ind: 'roman', auto: true, openheart: true,
    blurb: 'A Swiss automatic with an open-heart window, so you can watch the balance wheel beat.',
    feats: ['Swiss automatic movement', 'Open-heart dial', 'Exhibition case back', 'Sapphire crystal'],
    v: [V('Silver / Brown', 'silver', 'steel', 'brown', '#1d1d1f', '#dcdde0'), V('Blue / Black', 'navy', 'steel', 'black', '#ffffff', '#15213b')] },
  { b: 'Xylys', m: 'Belvedere Automatic', ref: '', cat: 'xylys', s: 'dress', p: 75900, mrp: 75900, st: 'metal', size: '42 mm', wr: '100m', mv: 'Swiss Automatic', glass: 'Sapphire Crystal', pop: 6, ind: 'stick', auto: true, date: true,
    blurb: 'The flagship Xylys - Belvedere Automatic, with a refined steel case and Swiss automatic movement.',
    feats: ['Swiss automatic movement', 'Exhibition case back', 'Sapphire crystal', 'Date window'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Black', 'black', 'steel', 'steel', '#ffffff')] },
  { b: 'Xylys', m: 'Seraphina Women', ref: '', cat: 'xylys', s: 'dress', p: 24150, mrp: 34500, st: 'metal', size: '30 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 7, small: true, ind: 'dots', women: true,
    blurb: 'Xylys Seraphina - graceful, feminine and Swiss made, with a mother-of-pearl dial.',
    feats: ['Mother-of-pearl dial', 'Swiss made', 'Sapphire crystal'],
    v: [V('Rose Gold', 'mop', 'rose', 'rose', '#6b3a2e', '#d9937f'), V('Two-Tone', 'mop', 'gold', 'steel', '#3a2a05', '#d4af37')] },
  { b: 'Xylys', m: 'Genevieve Women', ref: '', cat: 'xylys', s: 'dress', p: 12480, mrp: 17830, st: 'mesh', size: '28 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 6, small: true, ind: 'stick', women: true,
    blurb: 'A slim Swiss watch for her on a fine mesh bracelet - everyday luxury.',
    feats: ['Swiss made', 'Mesh bracelet', 'Sapphire crystal'],
    v: [V('Rose Gold', 'pink', 'rose', 'rose', '#6b3a2e', '#d9937f'), V('Silver', 'white', 'steel', 'steel', '#1d1d1f', '#dcdde0')] },

  // ================= TITAN EDGE / STELLAR / MARITIME =================
  { b: 'Titan', dn: 'TITAN EDGE', m: 'Edge Mechanical Ultra-Slim', ref: '1811WL01', cat: 'titanlux', s: 'dress', p: 212500, mrp: 212500, st: 'leather', size: '40 mm', wr: '30m', mv: 'Hand-wound Mechanical (in-house)', glass: 'Sapphire Crystal', pop: 8, ind: 'none', auto: true,
    blurb: "Titan's slimmest mechanical watch - a hand-wound, in-house movement in a titanium case only a few millimetres thick.",
    feats: ['In-house hand-wound movement', 'Ultra-slim titanium case', 'Sapphire crystal', 'Leather strap'],
    v: [V('Black Dial', 'black', '#b8babd', 'black', '#c9ccd1')] },
  { b: 'Titan', dn: 'TITAN EDGE', m: 'Edge Ceramic Men', ref: '', cat: 'titanlux', s: 'dress', p: 25195, mrp: 35995, st: 'metal', size: '40 mm', wr: '30m', mv: 'Slim Quartz', glass: 'Sapphire Crystal', pop: 8, ind: 'none',
    blurb: 'Titan Edge in high-tech ceramic - slim, smooth and scratch-resistant.',
    feats: ['Ultra-slim case', 'Ceramic bracelet', 'Sapphire crystal'],
    v: [V('Silver / Grey', 'silver', '#6e7075', '#6e7075', '#1d1d1f', '#6e7075'), V('Black', 'black', 'ceramic', 'ceramic', '#c9ccd1', '#1a1a1c')] },
  { b: 'Titan', dn: 'TITAN EDGE', m: 'Edge Bicolour Green Ceramic', ref: '', cat: 'titanlux', s: 'dress', p: 26595, mrp: 37995, st: 'metal', size: '40 mm', wr: '30m', mv: 'Slim Quartz', glass: 'Sapphire Crystal', pop: 7, ind: 'none',
    blurb: 'A bold green ceramic Edge with a two-tone finish - modern luxury from Titan.',
    feats: ['Green ceramic bracelet', 'Ultra-slim profile', 'Sapphire crystal'],
    v: [V('Green', 'green', '#1f4d3a', '#1f4d3a', '#ffffff')] },
  { b: 'Titan', dn: 'TITAN EDGE', m: 'Edge Ceramic Glossy Green', ref: '', cat: 'titanlux', s: 'dress', p: 36495, mrp: 36495, st: 'metal', size: '40 mm', wr: '30m', mv: 'Slim Quartz', glass: 'Sapphire Crystal', pop: 6, ind: 'stick',
    blurb: 'A glossy green dial on a slim ceramic Edge - quietly eye-catching.',
    feats: ['Glossy dial', 'Ceramic bracelet', 'Sapphire crystal'],
    v: [V('Glossy Green', 'dgreen', 'ceramic', 'ceramic', '#d4af37', '#123a2c')] },
  { b: 'Titan', dn: 'TITAN EDGE', m: 'Edge Ceramic Women', ref: '2653NC01', cat: 'titanlux', s: 'dress', p: 18895, mrp: 26995, st: 'metal', size: '32 mm', wr: '30m', mv: 'Slim Quartz', glass: 'Sapphire Crystal', pop: 7, small: true, ind: 'none', women: true,
    blurb: 'Titan Edge Ceramic for her - feather-light, slim and elegant.',
    feats: ['Ceramic bracelet', 'Ultra-slim case', 'Sapphire crystal'],
    v: [V('Blue', 'blue', '#1e2f5c', '#1e2f5c', '#ffffff'), V('Black', 'black', 'ceramic', 'ceramic', '#c9ccd1', '#1a1a1c')] },
  { b: 'Titan', dn: 'TITAN EDGE', m: 'Edge Baseline Leather', ref: '', cat: 'titanlux', s: 'dress', p: 14695, mrp: 14695, st: 'leather', size: '40 mm', wr: '30m', mv: 'Slim Quartz', glass: 'Sapphire Crystal', pop: 7, ind: 'stick',
    blurb: 'The classic Titan Edge - one of the slimmest quartz watches in the world, on a fine leather strap.',
    feats: ['Ultra-slim case', 'Sapphire crystal', 'Leather strap'],
    v: [V('Black', 'black', 'steel', 'black', '#c9ccd1'), V('White / Brown', 'white', 'rose', 'brown', '#1d1d1f', '#6b4226')] },
  { b: 'Titan', m: 'Stellar 3.0 Wandering Hours Automatic', ref: '', cat: 'titanlux', s: 'dress', p: 179995, mrp: 179995, st: 'leather', size: '43 mm', wr: '50m', mv: 'Automatic, Wandering Hours', glass: 'Sapphire Crystal', pop: 8, ind: 'none', auto: true, openheart: true,
    blurb: "India's first wandering-hours watch - the Stellar 3.0 shows the hour on a disc that travels across the dial, in a crystallised titanium case.",
    feats: ['Wandering hours complication', 'Automatic movement', 'Crystallised titanium case', 'Sapphire crystal'],
    v: [V('Midnight Blue', 'navy', '#9da0a5', 'navy', '#d4af37', '#15213b')] },
  { b: 'Titan', m: 'Stellar Celestial Multifunction', ref: '', cat: 'titanlux', s: 'chrono', p: 44545, mrp: 44545, st: 'leather', size: '44 mm', wr: '50m', mv: 'Quartz Multifunction', glass: 'Sapphire Crystal', pop: 6, ind: 'roman',
    blurb: 'Inspired by the night sky, Titan Stellar uses celestial dials and bold multifunction layouts. (Top of the Stellar range)',
    feats: ['Celestial dial', 'Multifunction sub-dials', 'Sapphire crystal', 'Leather strap'],
    v: [V('Galaxy Blue', 'navy', 'steel', 'black', '#d4af37', '#15213b'), V('Black / Gold', 'black', 'gold', 'brown', '#d4af37', '#151515')] },
  { b: 'Titan', m: 'Stellar Analog', ref: '', cat: 'titanlux', s: 'dress', p: 7450, mrp: 7450, st: 'leather', size: '42 mm', wr: '50m', mv: 'Quartz', glass: 'Mineral Glass', pop: 6, ind: 'stick', date: true,
    blurb: 'The entry to the Titan Stellar collection - space-inspired detailing at an accessible price.',
    feats: ['Space-inspired dial', 'Date window', 'Leather strap'],
    v: [V('Blue', 'blue', 'steel', 'brown', '#ffffff', '#1d4f8c'), V('Black', 'black', 'gun', 'black', '#ff6b1a')] },
  { b: 'Titan', m: 'Maritime Diver Automatic', ref: '', cat: 'titanlux', s: 'diver', p: 38795, mrp: 38795, st: 'metal', size: '44 mm', wr: '200m', mv: 'Automatic', glass: 'Sapphire Crystal', pop: 7, ind: 'stick', date: true, auto: true,
    blurb: "Titan Maritime - built for the sea, with a rotating diver's bezel. (Top of the Maritime range)",
    feats: ['Automatic movement', 'Unidirectional diver bezel', 'Luminous markers', 'Sapphire crystal'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Black', 'black', 'steel', 'steel', '#ffffff')] },
  { b: 'Titan', m: 'Maritime Quartz', ref: '', cat: 'titanlux', s: 'diver', p: 9450, mrp: 9450, st: 'rubber', size: '44 mm', wr: '100m', mv: 'Quartz', glass: 'Mineral Glass', pop: 6, ind: 'stick', date: true,
    blurb: 'The ocean-inspired Maritime look in an everyday quartz watch. (Entry Maritime price)',
    feats: ['Rotating bezel', 'Date window', 'Silicone strap'],
    v: [V('Navy', 'navy', 'steel', 'navy', '#ffffff', '#15213b'), V('Green', 'green', 'steel', 'dgreen', '#ffffff')] },

  // ================= RADO =================
  { b: 'Rado', m: 'Captain Cook Automatic', ref: '', cat: 'swiss', s: 'diver', p: 220000, mrp: 220000, st: 'metal', size: '42 mm', wr: '300m', mv: 'Automatic, ~80 h power reserve', glass: 'Sapphire Crystal', pop: 9, ind: 'stick', date: true,
    blurb: 'A 1962 diver reborn - the Captain Cook has a ceramic bezel, 80-hour automatic movement and a sunray dial.',
    feats: ['Automatic, ~80 h power reserve', 'High-tech ceramic bezel', '300m water resistance', 'Nivachron hairspring'],
    v: [V('Green', 'green', 'steel', 'steel', '#ffffff'), V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Black', 'black', 'steel', 'steel', '#ffffff')] },
  { b: 'Rado', m: 'Captain Cook High-Tech Ceramic', ref: '', cat: 'swiss', s: 'diver', p: 390000, mrp: 390000, st: 'metal', size: '43 mm', wr: '300m', mv: 'Automatic', glass: 'Sapphire Crystal', pop: 7, ind: 'stick', date: true,
    blurb: 'An all-ceramic Captain Cook - incredibly scratch-resistant and comfortable on the wrist. (Approx. price)',
    feats: ['Monobloc high-tech ceramic case', 'Automatic movement', '300m water resistance'],
    v: [V('Black Ceramic', 'black', 'ceramic', 'ceramic', '#ffffff', '#1a1a1c'), V('Blue Ceramic', 'navy', '#1e2f5c', '#1e2f5c', '#ffffff', '#1e2f5c')] },
  { b: 'Rado', m: 'Captain Cook Chronograph', ref: '', cat: 'swiss', s: 'chrono', p: 530000, mrp: 530000, st: 'metal', size: '43 mm', wr: '300m', mv: 'Automatic Chronograph', glass: 'Sapphire Crystal', pop: 6, ind: 'stick', tachy: true,
    blurb: 'The top of the Captain Cook range - a ceramic automatic chronograph.',
    feats: ['Automatic chronograph', 'High-tech ceramic', '300m water resistance'],
    v: [V('Black', 'black', 'ceramic', 'ceramic', '#ff6b1a', '#1a1a1c')] },
  { b: 'Rado', m: 'Centrix Automatic', ref: '', cat: 'swiss', s: 'dress', p: 135000, mrp: 135000, st: 'metal', size: '40 mm', wr: '50m', mv: 'Automatic', glass: 'Sapphire Crystal', pop: 8, ind: 'stick', date: true, auto: true,
    blurb: 'Rado Centrix - a classic shape, ceramic and steel bracelet and a Swiss automatic movement. (Approx. price)',
    feats: ['Automatic movement', 'Steel & ceramic bracelet', 'Sapphire crystal', 'Date window'],
    v: [V('Black', 'black', 'steel', 'steel', '#ffffff'), V('Blue', 'blue', 'steel', 'steel', '#ffffff')] },
  { b: 'Rado', m: 'Centrix Diamonds Women', ref: '', cat: 'swiss', s: 'dress', p: 110000, mrp: 110000, st: 'metal', size: '30.5 mm', wr: '50m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 8, small: true, ind: 'dots', women: true,
    blurb: "One of Rado's best-loved women's watches - Centrix with diamond indices and a mother-of-pearl dial.",
    feats: ['Diamond indices', 'Mother-of-pearl dial', 'Ceramic & steel bracelet', 'Sapphire crystal'],
    v: [V('White MOP / Rose Gold', 'mop', 'rose', 'rose', '#6b3a2e', '#d9937f'), V('Black / Steel', 'black', 'steel', 'steel', '#c9ccd1')] },
  { b: 'Rado', m: 'True Square Automatic', ref: '', cat: 'swiss', s: 'dress', sq: true, p: 200000, mrp: 200000, st: 'metal', size: '38 × 44.2 mm', wr: '50m', mv: 'Automatic', glass: 'Sapphire Crystal', pop: 8, ind: 'none', auto: true,
    blurb: 'A perfect square of high-tech ceramic - the True Square is a modern design icon.',
    feats: ['High-tech ceramic case', 'Automatic movement', 'Sapphire crystal'],
    v: [V('Black Ceramic', 'black', 'ceramic', 'ceramic', '#c9ccd1', '#1a1a1c'), V('White Ceramic', 'white', '#f1f1f1', '#f1f1f1', '#1d1d1f')] },
  { b: 'Rado', m: 'True Square Open Heart', ref: '', cat: 'swiss', s: 'dress', sq: true, p: 260000, mrp: 260000, st: 'metal', size: '38 × 44.2 mm', wr: '50m', mv: 'Automatic', glass: 'Sapphire Crystal', pop: 6, ind: 'none', auto: true, openheart: true,
    blurb: 'True Square with an open heart, showing the beating automatic movement through the dial.',
    feats: ['Open-heart dial', 'High-tech ceramic', 'Automatic movement'],
    v: [V('Black', 'black', 'ceramic', 'ceramic', '#d4af37', '#1a1a1c')] },
  { b: 'Rado', m: 'True Square Skeleton', ref: '', cat: 'swiss', s: 'dress', sq: true, p: 300000, mrp: 300000, st: 'metal', size: '38 × 44.2 mm', wr: '50m', mv: 'Automatic Skeleton', glass: 'Sapphire Crystal', pop: 5, ind: 'none', auto: true, openheart: true,
    blurb: 'A fully skeletonised True Square - every gear on display.',
    feats: ['Skeleton automatic movement', 'High-tech ceramic', 'Sapphire crystal'],
    v: [V('Grey', 'grey', '#4a4d52', '#4a4d52', '#ff6b1a', '#4a4d52')] },
  { b: 'Rado', m: 'HyperChrome Classic Automatic', ref: '', cat: 'swiss', s: 'dress', p: 264600, mrp: 264600, st: 'metal', size: '42 mm', wr: '100m', mv: 'Automatic', glass: 'Sapphire Crystal', pop: 6, ind: 'stick', date: true, auto: true,
    blurb: 'Rado HyperChrome - polished high-tech ceramic with a sporty, timeless look.',
    feats: ['High-tech ceramic', 'Automatic movement', 'Date window'],
    v: [V('Black', 'black', 'ceramic', 'ceramic', '#c9ccd1', '#1a1a1c'), V('Blue', 'navy', '#1e2f5c', '#1e2f5c', '#ffffff', '#1e2f5c')] },
  { b: 'Rado', m: 'HyperChrome Chronograph', ref: '', cat: 'swiss', s: 'chrono', p: 210000, mrp: 210000, st: 'metal', size: '45 mm', wr: '100m', mv: 'Swiss Chronograph', glass: 'Sapphire Crystal', pop: 6, ind: 'stick', date: true,
    blurb: 'A sporty HyperChrome chronograph in light, scratch-proof ceramic. (Approx. price)',
    feats: ['Chronograph', 'High-tech ceramic', 'Sapphire crystal'],
    v: [V('Black', 'black', 'ceramic', 'ceramic', '#e03131', '#1a1a1c')] },

  // ================= LONGINES =================
  { b: 'Longines', m: 'HydroConquest 41', ref: '', cat: 'swiss', s: 'diver', p: 156000, mrp: 156000, st: 'metal', size: '41 mm', wr: '300m', mv: 'Automatic', glass: 'Sapphire Crystal', pop: 9, ind: 'arabic', date: true, auto: true,
    blurb: "India's bestselling Swiss dive watch under ₹2 lakh - ceramic bezel, 300m water resistance and an automatic movement.",
    feats: ['Automatic movement', 'Ceramic bezel', '300m water resistance', 'Sapphire crystal'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Black', 'black', 'steel', 'steel', '#ffffff'), V('Green', 'green', 'steel', 'steel', '#ffffff')] },
  { b: 'Longines', m: 'HydroConquest GMT', ref: '', cat: 'swiss', s: 'diver', p: 249000, mrp: 249000, st: 'metal', size: '41 mm', wr: '300m', mv: 'Automatic GMT', glass: 'Sapphire Crystal', pop: 7, ind: 'arabic', date: true, gmt: true,
    blurb: 'HydroConquest with a second time zone - ideal for travellers. (Approx. price)',
    feats: ['GMT second time zone', 'Automatic movement', '300m water resistance'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Black', 'black', 'steel', 'steel', '#ffffff')] },
  { b: 'Longines', m: 'Master Collection Moonphase', ref: '', cat: 'swiss', s: 'chrono', p: 285000, mrp: 285000, st: 'leather', size: '40 mm', wr: '30m', mv: 'Automatic Moonphase', glass: 'Sapphire Crystal', pop: 8, ind: 'arabic',
    blurb: 'Longines Master Collection - a classic barleycorn dial with moonphase and calendar. (Approx. price)',
    feats: ['Automatic movement', 'Moonphase & calendar', 'Barleycorn dial', 'Exhibition case back'],
    v: [V('Silver / Brown', 'silver', 'steel', 'brown', '#1d4f8c', '#dcdde0'), V('Blue / Black', 'blue', 'steel', 'black', '#ffffff')] },
  { b: 'Longines', m: 'Master Collection Automatic', ref: '', cat: 'swiss', s: 'dress', p: 180000, mrp: 180000, st: 'leather', size: '40 mm', wr: '30m', mv: 'Automatic', glass: 'Sapphire Crystal', pop: 7, ind: 'arabic', date: true, auto: true,
    blurb: 'Pure Longines elegance - automatic movement, sapphire crystal and a refined leather strap.',
    feats: ['Automatic movement', 'Barleycorn dial', 'Sapphire crystal'],
    v: [V('Silver', 'silver', 'steel', 'brown', '#1d4f8c', '#dcdde0')] },
  { b: 'Longines', m: 'Spirit Pilot', ref: '', cat: 'swiss', s: 'field', p: 240000, mrp: 240000, st: 'metal', size: '40 mm', wr: '100m', mv: 'Automatic Chronometer', glass: 'Sapphire Crystal', pop: 7, ind: 'field', date: true, auto: true,
    blurb: 'Inspired by aviation pioneers, Longines Spirit is a certified chronometer pilot watch. (Approx. price)',
    feats: ['Certified chronometer', 'Automatic movement', 'Pilot dial', '100m water resistance'],
    v: [V('Black', 'black', 'steel', 'steel', '#ffffff'), V('Blue', 'navy', 'steel', 'brown', '#ffffff', '#15213b')] },
  { b: 'Longines', m: 'Conquest', ref: '', cat: 'swiss', s: 'dress', p: 140000, mrp: 140000, st: 'metal', size: '41 mm', wr: '100m', mv: 'Automatic', glass: 'Sapphire Crystal', pop: 7, ind: 'stick', date: true, auto: true,
    blurb: 'The sporty, everyday Longines - bold dial, automatic movement. (Entry Conquest price)',
    feats: ['Automatic movement', '100m water resistance', 'Sapphire crystal'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Black', 'black', 'steel', 'steel', '#ffffff'), V('Silver', 'silver', 'steel', 'steel', '#1d1d1f', '#dcdde0')] },
  { b: 'Longines', m: 'PrimaLuna Women', ref: '', cat: 'swiss', s: 'dress', p: 125000, mrp: 125000, st: 'metal', size: '30.5 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 7, small: true, ind: 'dots', women: true,
    blurb: "PrimaLuna - Longines' graceful women's collection with a mother-of-pearl dial. (Approx. price)",
    feats: ['Mother-of-pearl dial', 'Diamond indices', 'Sapphire crystal'],
    v: [V('MOP / Steel', 'mop', 'steel', 'steel', '#1d1d1f', '#f3eee8'), V('MOP / Two-Tone', 'mop', 'gold', 'steel', '#3a2a05', '#d4af37')] },

  // ================= TISSOT =================
  { b: 'Tissot', m: 'PRX Powermatic 80', ref: 'T137.407.11.041.00', cat: 'swiss', s: 'dress', p: 57000, mrp: 57000, st: 'metal', size: '40 mm', wr: '100m', mv: 'Automatic, Powermatic 80', glass: 'Sapphire Crystal', pop: 10, ind: 'stick', date: true, auto: true,
    blurb: '1970s integrated-bracelet style, waffle dial and an 80-hour automatic - one of the hottest watches of the decade.',
    feats: ['Powermatic 80 automatic (80 h reserve)', 'Integrated bracelet', 'Waffle-pattern dial', 'Sapphire crystal'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Ice Blue', 'ice', 'steel', 'steel', '#1d1d1f'), V('Green', 'green', 'steel', 'steel', '#ffffff'), V('Black', 'black', 'steel', 'steel', '#ffffff')] },
  { b: 'Tissot', m: 'PRX Quartz 40', ref: 'T137.410.11.041.00', cat: 'swiss', s: 'dress', p: 37000, mrp: 37000, st: 'metal', size: '40 mm', wr: '100m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 9, ind: 'stick', date: true,
    blurb: 'The iconic PRX look with a slim Swiss quartz movement. (Approx. price)',
    feats: ['Swiss quartz', 'Integrated bracelet', 'Sapphire crystal'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Silver', 'silver', 'steel', 'steel', '#1d1d1f'), V('Gold', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37')] },
  { b: 'Tissot', m: 'Seastar 1000 Powermatic 80', ref: '', cat: 'swiss', s: 'diver', p: 72000, mrp: 72000, st: 'metal', size: '43 mm', wr: '300m', mv: 'Automatic, Powermatic 80', glass: 'Sapphire Crystal', pop: 8, ind: 'stick', date: true, auto: true,
    blurb: 'A real 300m dive watch with an 80-hour automatic - one of the best-value Swiss divers. (Approx. price)',
    feats: ['Powermatic 80 automatic', 'Ceramic bezel', '300m water resistance'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Black', 'black', 'steel', 'steel', '#ffffff')] },
  { b: 'Tissot', m: 'Seastar 1000 Quartz 36', ref: '', cat: 'swiss', s: 'diver', p: 48500, mrp: 48500, st: 'metal', size: '36 mm', wr: '300m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 7, ind: 'stick', date: true,
    blurb: 'The Seastar diver look in a compact 36mm size with a Swiss quartz movement.',
    feats: ['300m water resistance', 'Rotating bezel', 'Sapphire crystal'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Green', 'green', 'steel', 'steel', '#ffffff')] },
  { b: 'Tissot', m: 'Gentleman Powermatic 80', ref: '', cat: 'swiss', s: 'dress', p: 57000, mrp: 57000, st: 'metal', size: '40 mm', wr: '100m', mv: 'Automatic, Powermatic 80 Silicium', glass: 'Sapphire Crystal', pop: 8, ind: 'stick', date: true, auto: true,
    blurb: 'Tissot Gentleman - a versatile automatic for office and weekends, with a silicon balance spring.',
    feats: ['Powermatic 80 Silicium', 'Sapphire crystal', '100m water resistance'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Black', 'black', 'steel', 'steel', '#ffffff'), V('Silver', 'silver', 'steel', 'steel', '#1d1d1f')] },
  { b: 'Tissot', m: 'Le Locle Powermatic 80', ref: '', cat: 'swiss', s: 'dress', p: 57000, mrp: 57000, st: 'metal', size: '39.3 mm', wr: '30m', mv: 'Automatic, Powermatic 80', glass: 'Sapphire Crystal', pop: 7, ind: 'roman', date: true, auto: true,
    blurb: "Named after Tissot's hometown - a classic Roman-numeral dress watch with a guilloché dial.",
    feats: ['Powermatic 80 automatic', 'Guilloché dial', 'Exhibition case back'],
    v: [V('Silver', 'silver', 'steel', 'steel', '#1d1d1f', '#dcdde0'), V('Black / Leather', 'black', 'steel', 'black', '#c9ccd1')] },
  { b: 'Tissot', m: 'PR 100 Chronograph', ref: '', cat: 'swiss', s: 'chrono', p: 48000, mrp: 48000, st: 'metal', size: '40 mm', wr: '100m', mv: 'Swiss Chronograph Quartz', glass: 'Sapphire Crystal', pop: 7, ind: 'stick', date: true,
    blurb: 'A clean, sporty Swiss chronograph for everyday wear.',
    feats: ['Chronograph', 'Sapphire crystal', '100m water resistance'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Black', 'black', 'steel', 'steel', '#ffffff')] },
  { b: 'Tissot', m: 'PR 100 Women', ref: '', cat: 'swiss', s: 'dress', p: 31000, mrp: 31000, st: 'metal', size: '34 mm', wr: '100m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 7, small: true, ind: 'stick', date: true, women: true,
    blurb: 'A refined everyday Swiss watch for her with a sunray dial. (Approx. price)',
    feats: ['Swiss quartz', 'Sapphire crystal', '100m water resistance'],
    v: [V('Silver', 'silver', 'steel', 'steel', '#1d1d1f'), V('Mint', '#a6e8cf', 'steel', 'steel', '#1d1d1f', '#a6e8cf')] },

  // ================= FREDERIQUE CONSTANT =================
  { b: 'Frederique Constant', dn: 'F.CONSTANT', m: 'Classics Quartz Chronograph', ref: '', cat: 'swiss', s: 'chrono', p: 101700, mrp: 101700, st: 'leather', size: '42 mm', wr: '50m', mv: 'Swiss Chronograph Quartz', glass: 'Sapphire Crystal', pop: 6, ind: 'roman', date: true,
    blurb: 'Geneva elegance - a classic chronograph with Roman numerals and a guilloché centre.',
    feats: ['Swiss chronograph', 'Guilloché dial', 'Sapphire crystal'],
    v: [V('Silver / Blue', 'silver', 'steel', 'navy', '#1d4f8c', '#dcdde0'), V('Navy / Brown', 'navy', 'rose', 'brown', '#ffffff', '#15213b')] },
  { b: 'Frederique Constant', dn: 'F.CONSTANT', m: 'Classics Heart Beat Automatic', ref: '', cat: 'swiss', s: 'dress', p: 160000, mrp: 160000, st: 'leather', size: '40 mm', wr: '50m', mv: 'Automatic', glass: 'Sapphire Crystal', pop: 6, ind: 'roman', auto: true, openheart: true,
    blurb: 'The "Heart Beat" window shows the automatic movement at work - a Frederique Constant signature. (Approx. price)',
    feats: ['Open heart window', 'Automatic movement', 'Guilloché dial'],
    v: [V('Silver / Brown', 'silver', 'rose', 'brown', '#3a2a05', '#dcdde0')] },

  // ================= MOVADO =================
  { b: 'Movado', m: 'Museum Classic', ref: '', cat: 'swiss', s: 'dress', p: 60000, mrp: 60000, st: 'leather', size: '40 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 8, ind: 'museum',
    blurb: "The famous Museum dial - just a single dot at 12 o'clock. Part of the permanent collection of New York's MoMA since 1960.",
    feats: ['Iconic Museum dot dial', 'Swiss quartz', 'Sapphire crystal', 'Leather strap'],
    v: [V('Black / Steel', 'black', 'steel', 'black', '#c9ccd1'), V('Black / Gold', 'black', 'gold', 'black', '#d4af37', '#d4af37')] },
  { b: 'Movado', m: 'Museum Classic Women', ref: '', cat: 'swiss', s: 'dress', p: 62000, mrp: 62000, st: 'metal', size: '28 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 7, small: true, ind: 'museum', women: true,
    blurb: 'The Museum dial in a petite size for her - pure minimalism. (Approx. price)',
    feats: ['Museum dot dial', 'Swiss quartz', 'Steel bracelet'],
    v: [V('Black / Gold', 'black', 'gold', 'gold', '#d4af37', '#d4af37'), V('Silver / Steel', 'silver', 'steel', 'steel', '#1d1d1f')] },
  { b: 'Movado', m: 'Heritage Automatic', ref: '', cat: 'swiss', s: 'dress', p: 112125, mrp: 112125, st: 'leather', size: '40 mm', wr: '30m', mv: 'Swiss Automatic', glass: 'Sapphire Crystal', pop: 5, ind: 'arabic', auto: true, date: true,
    blurb: 'Inspired by Movado archive pieces - a vintage-style Swiss automatic.',
    feats: ['Swiss automatic', 'Vintage-inspired dial', 'Leather strap'],
    v: [V('Silver / Brown', 'silver', 'steel', 'brown', '#1d1d1f', '#dcdde0')] },

  // ================= DESIGNER BRANDS (approx. prices) =================
  { b: 'Hugo Boss', dn: 'BOSS', m: 'Grand Prix Chronograph', ref: '', cat: 'designer', s: 'chrono', p: 21500, mrp: 21500, st: 'metal', size: '44 mm', wr: '50m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 8, ind: 'stick', date: true, tachy: true,
    blurb: 'BOSS Grand Prix - a sharp, racing-inspired chronograph with a tachymeter bezel. (Approx. price)',
    feats: ['Chronograph', 'Tachymeter bezel', 'Steel bracelet'],
    v: [V('Black', 'black', 'steel', 'steel', '#e03131'), V('Blue', 'navy', 'steel', 'steel', '#ffffff', '#15213b')] },
  { b: 'Hugo Boss', dn: 'BOSS', m: 'Hero Sport Lux', ref: '', cat: 'designer', s: 'chrono', p: 24000, mrp: 24000, st: 'metal', size: '43 mm', wr: '50m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 7, ind: 'stick', date: true,
    blurb: 'A sporty-luxury BOSS chronograph with a bold bezel. (Approx. price)',
    feats: ['Chronograph', 'Date window', 'Steel bracelet'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Black / Gold', 'black', 'gold', 'gold', '#d4af37')] },
  { b: 'Hugo Boss', dn: 'BOSS', m: 'Elite Mesh', ref: '', cat: 'designer', s: 'dress', p: 17500, mrp: 17500, st: 'mesh', size: '41 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 6, ind: 'stick', date: true,
    blurb: 'A slim, smart BOSS dress watch on a mesh bracelet. (Approx. price)',
    feats: ['Mesh bracelet', 'Slim case', 'Date window'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Black', 'black', 'gun', 'gun', '#c9ccd1')] },
  { b: 'Hugo Boss', dn: 'BOSS', m: 'Women Signature', ref: '', cat: 'designer', s: 'dress', p: 18500, mrp: 18500, st: 'metal', size: '34 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 6, small: true, ind: 'dots', women: true,
    blurb: 'A polished BOSS watch for her with crystal markers. (Approx. price)',
    feats: ['Crystal markers', 'Steel bracelet'],
    v: [V('Rose Gold', 'mop', 'rose', 'rose', '#6b3a2e', '#d9937f'), V('Silver', 'white', 'steel', 'steel', '#1d1d1f')] },
  { b: 'Coach', m: 'Grand Women', ref: '', cat: 'designer', s: 'dress', p: 16500, mrp: 16500, st: 'metal', size: '36 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 7, small: true, ind: 'dots', women: true,
    blurb: 'Coach Grand - a crystal-set bezel and signature design for everyday glamour. (Approx. price)',
    feats: ['Crystal-set bezel', 'Steel bracelet'],
    v: [V('Gold', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37'), V('Rose Gold', 'pink', 'rose', 'rose', '#6b3a2e', '#d9937f')] },
  { b: 'Coach', m: 'Park Women', ref: '', cat: 'designer', s: 'dress', p: 14500, mrp: 14500, st: 'leather', size: '34 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 6, small: true, ind: 'arabic', women: true,
    blurb: 'A classic Coach watch on a leather strap. (Approx. price)',
    feats: ['Leather strap', 'Signature design'],
    v: [V('Cream / Tan', 'cream', 'gold', 'tan', '#3a2a05', '#a8703d'), V('White / Black', 'white', 'steel', 'black', '#1d1d1f')] },
  { b: 'Coach', m: 'Cary Women', ref: '', cat: 'designer', s: 'dress', p: 18500, mrp: 18500, st: 'metal', size: '34 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 6, small: true, ind: 'stick', women: true,
    blurb: 'Coach Cary - clean and modern, with a sunray dial. (Approx. price)',
    feats: ['Sunray dial', 'Steel bracelet'],
    v: [V('Silver', 'silver', 'steel', 'steel', '#1d1d1f'), V('Gold', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37')] },
  { b: 'Coach', m: 'Reese Square Women', ref: '', cat: 'designer', s: 'dress', sq: true, p: 17500, mrp: 17500, st: 'metal', size: '28 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 5, small: true, ind: 'none', women: true,
    blurb: 'A square, Art Deco-inspired Coach watch for her. (Approx. price)',
    feats: ['Square case', 'Steel bracelet'],
    v: [V('Gold', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37')] },
  { b: 'Michael Kors', m: 'Lexington Chronograph', ref: 'MK8281', cat: 'designer', s: 'chrono', p: 26995, mrp: 26995, st: 'metal', size: '44 mm', wr: '50m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 8, ind: 'stick', date: true,
    blurb: 'Michael Kors Lexington - an all-gold statement chronograph. (Approx. price)',
    feats: ['Chronograph', 'Gold-tone steel', 'Date window'],
    v: [V('Gold', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37'), V('Black / Gold', 'black', 'gold', 'gold', '#d4af37', '#151515')] },
  { b: 'Michael Kors', m: 'Lexington Women', ref: 'MK5955', cat: 'designer', s: 'chrono', p: 24995, mrp: 24995, st: 'metal', size: '38 mm', wr: '50m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 7, small: true, ind: 'dots', women: true,
    blurb: 'A two-tone Lexington chronograph with crystal accents, made for her. (Approx. price)',
    feats: ['Chronograph', 'Crystal accents', 'Two-tone bracelet'],
    v: [V('Two-Tone', 'silver', 'gold', 'steel', '#3a2a05', '#d4af37'), V('Rose Gold', 'pink', 'rose', 'rose', '#6b3a2e', '#d9937f')] },
  { b: 'Michael Kors', m: 'Darci Women', ref: '', cat: 'designer', s: 'dress', p: 21995, mrp: 21995, st: 'metal', size: '39 mm', wr: '50m', mv: 'Quartz', glass: 'Mineral Glass', pop: 7, small: true, ind: 'none', women: true, fluted: true,
    blurb: 'Darci - a pavé crystal bezel that sparkles all day. (Approx. price)',
    feats: ['Pavé crystal bezel', 'Steel bracelet'],
    v: [V('Gold', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37'), V('Rose Gold', 'pink', 'rose', 'rose', '#6b3a2e', '#d9937f')] },
  { b: 'Michael Kors', m: 'Runway Women', ref: '', cat: 'designer', s: 'dress', p: 18995, mrp: 18995, st: 'metal', size: '38 mm', wr: '50m', mv: 'Quartz', glass: 'Mineral Glass', pop: 7, small: true, ind: 'stick', women: true,
    blurb: 'The Runway - a sleek, best-selling Michael Kors design. (Approx. price)',
    feats: ['Steel bracelet', 'Minimal dial'],
    v: [V('Gold', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37'), V('Silver', 'white', 'steel', 'steel', '#1d1d1f')] },
  { b: 'Armani Exchange', dn: 'A|X', m: 'Hampton Chronograph', ref: 'AX2104', cat: 'designer', s: 'chrono', p: 15995, mrp: 15995, st: 'metal', size: '46 mm', wr: '50m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 8, ind: 'stick', date: true,
    blurb: 'The all-black Hampton - a bold fashion chronograph. (Approx. price)',
    feats: ['Chronograph', 'Date window', 'Steel bracelet'],
    v: [V('All Black', 'black', '#2b2b2b', '#2b2b2b', '#c9ccd1', '#2b2b2b'), V('Steel / Blue', 'blue', 'steel', 'steel', '#ffffff')] },
  { b: 'Emporio Armani', dn: 'EMPORIO ARMANI', m: 'Renato Chronograph', ref: '', cat: 'designer', s: 'chrono', p: 29995, mrp: 29995, st: 'leather', size: '43 mm', wr: '50m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 7, ind: 'stick',
    blurb: 'Emporio Armani Renato - Italian style with a refined chronograph dial. (Approx. price)',
    feats: ['Chronograph', 'Leather strap', 'Italian design'],
    v: [V('Blue / Brown', 'blue', 'steel', 'brown', '#ffffff', '#1d4f8c'), V('Black', 'black', 'gun', 'black', '#c9ccd1')] },
  { b: 'Emporio Armani', dn: 'EMPORIO ARMANI', m: 'Gianni T-Bar Women', ref: '', cat: 'designer', s: 'dress', p: 22995, mrp: 22995, st: 'metal', size: '32 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 7, small: true, ind: 'dots', women: true,
    blurb: 'The elegant Gianni T-Bar for her, with a mother-of-pearl dial. (Approx. price)',
    feats: ['Mother-of-pearl dial', 'T-bar bracelet', 'Crystal markers'],
    v: [V('Rose Gold', 'mop', 'rose', 'rose', '#6b3a2e', '#d9937f'), V('Two-Tone', 'mop', 'gold', 'steel', '#3a2a05', '#d4af37')] },
  { b: 'Tommy Hilfiger', dn: 'TOMMY', m: 'Decker Multifunction', ref: 'TH1791349', cat: 'designer', s: 'chrono', p: 14999, mrp: 15999, st: 'leather', size: '44 mm', wr: '50m', mv: 'Quartz Multifunction', glass: 'Mineral Glass', pop: 7, ind: 'arabic',
    blurb: 'Classic American style with sporty sub-dials and signature Tommy colours. (Approx. price)',
    feats: ['Day, date & 24-hour sub-dials', 'Genuine leather strap'],
    v: [V('Navy / Brown', 'navy', 'steel', 'brown', '#e03131', '#15213b'), V('Black / Black', 'black', 'steel', 'black', '#e03131')] },
  { b: 'Kate Spade', m: 'Holland Women', ref: '', cat: 'designer', s: 'dress', p: 15995, mrp: 15995, st: 'metal', size: '34 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 6, small: true, ind: 'arabic', women: true,
    blurb: 'Playful and pretty - Kate Spade Holland. (Approx. price)',
    feats: ['Steel bracelet', 'Signature design'],
    v: [V('Gold', 'cream', 'gold', 'gold', '#3a2a05', '#d4af37'), V('Rose Gold', 'pink', 'rose', 'rose', '#6b3a2e', '#d9937f')] },
  // ================= MORE MODELS (approx. prices) =================
  { b: 'Tissot', m: 'Seastar 2000 Professional', ref: '', cat: 'swiss', s: 'diver', p: 115000, mrp: 115000, st: 'rubber', size: '46 mm', wr: '600m', mv: 'Automatic, Powermatic 80', glass: 'Sapphire Crystal', pop: 6, ind: 'stick', date: true, auto: true,
    blurb: "A serious 600m dive watch with a helium valve and ceramic bezel. (Approx. price)",
    feats: ['600m water resistance', 'Powermatic 80 automatic', 'Ceramic bezel'],
    v: [V('Black', 'black', 'steel', 'black', '#ffffff'), V('Blue', 'blue', 'steel', 'navy', '#ffffff')] },
  { b: 'Tissot', m: 'Supersport Chrono', ref: '', cat: 'swiss', s: 'chrono', p: 38000, mrp: 38000, st: 'metal', size: '45.5 mm', wr: '100m', mv: 'Swiss Chronograph Quartz', glass: 'Mineral Glass', pop: 7, ind: 'stick', date: true, tachy: true,
    blurb: "A bold, sporty Tissot chronograph with a tachymeter bezel. (Approx. price)",
    feats: ['Chronograph', 'Tachymeter bezel', '100m water resistance'],
    v: [V('Black', 'black', 'steel', 'steel', '#e03131'), V('Blue', 'blue', 'steel', 'steel', '#ffffff')] },
  { b: 'Tissot', m: 'Everytime 40', ref: '', cat: 'swiss', s: 'dress', p: 26000, mrp: 26000, st: 'metal', size: '40 mm', wr: '50m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 7, ind: 'arabic',
    blurb: "Simple, slim and Swiss - the easiest way into Swiss watches. (Approx. price)",
    feats: ['Swiss quartz', 'Sapphire crystal', 'Slim case'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('White', 'white', 'steel', 'steel', '#1d1d1f')] },
  { b: 'Tissot', m: 'Chrono XL Classic', ref: '', cat: 'swiss', s: 'chrono', p: 34000, mrp: 34000, st: 'leather', size: '45 mm', wr: '100m', mv: 'Swiss Chronograph Quartz', glass: 'Sapphire Crystal', pop: 7, ind: 'arabic', date: true,
    blurb: "A large, bold chronograph on a leather strap - classic Tissot sportiness. (Approx. price)",
    feats: ['Chronograph', 'Large 45mm case', 'Leather strap'],
    v: [V('Black / Brown', 'black', 'steel', 'brown', '#ffffff', '#6b4226'), V('Blue / Black', 'blue', 'steel', 'black', '#ffffff')] },
  { b: 'Tissot', m: 'PRX 35 Women', ref: '', cat: 'swiss', s: 'dress', p: 35000, mrp: 35000, st: 'metal', size: '35 mm', wr: '100m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 8, ind: 'stick', small: true, women: true, date: true,
    blurb: "The PRX in a smaller 35mm size - hugely popular with women. (Approx. price)",
    feats: ['Integrated bracelet', 'Swiss quartz', 'Sapphire crystal'],
    v: [V('Silver', 'silver', 'steel', 'steel', '#1d1d1f'), V('Rose Gold', 'pink', 'rose', 'rose', '#6b3a2e', '#d9937f'), V('Mint', '#a6e8cf', 'steel', 'steel', '#1d1d1f', '#a6e8cf')] },
  { b: 'Tissot', m: 'Bellissima Women', ref: '', cat: 'swiss', s: 'dress', p: 40000, mrp: 40000, st: 'metal', size: '29 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 6, ind: 'dots', small: true, women: true,
    blurb: "A delicate Tissot for her with mother-of-pearl and diamond accents. (Approx. price)",
    feats: ['Mother-of-pearl dial', 'Diamond indices', 'Sapphire crystal'],
    v: [V('MOP / Steel', 'mop', 'steel', 'steel', '#1d1d1f', '#f3eee8'), V('MOP / Rose Gold', 'mop', 'rose', 'rose', '#6b3a2e', '#d9937f')] },
  { b: 'Longines', m: 'Mini DolceVita Women', ref: '', cat: 'swiss', s: 'dress', p: 160000, mrp: 160000, st: 'leather', size: '21.5 × 29 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 8, ind: 'arabic', small: true, women: true, sq: true,
    blurb: "The rectangular Art Deco Longines - an elegant favourite for her. (Approx. price)",
    feats: ['Rectangular case', 'Sapphire crystal', 'Leather strap'],
    v: [V('Silver / Black', 'silver', 'steel', 'black', '#1d1d1f'), V('Silver / Brown', 'silver', 'rose', 'brown', '#1d1d1f', '#6b4226')] },
  { b: 'Longines', m: 'Legend Diver', ref: '', cat: 'swiss', s: 'diver', p: 260000, mrp: 260000, st: 'leather', size: '42 mm', wr: '300m', mv: 'Automatic', glass: 'Sapphire Crystal', pop: 6, ind: 'arabic', date: true, auto: true,
    blurb: "A 1960s super-compressor diver with an inner rotating bezel. (Approx. price)",
    feats: ['Automatic movement', 'Inner rotating bezel', '300m water resistance'],
    v: [V('Black', 'black', 'steel', 'black', '#ffffff'), V('Blue', 'blue', 'steel', 'navy', '#ffffff')] },
  { b: 'Longines', m: 'Conquest Chronograph', ref: '', cat: 'swiss', s: 'chrono', p: 230000, mrp: 230000, st: 'metal', size: '42 mm', wr: '100m', mv: 'Automatic Chronograph', glass: 'Sapphire Crystal', pop: 6, ind: 'stick', date: true,
    blurb: "A sporty automatic chronograph from the Conquest line. (Approx. price)",
    feats: ['Automatic chronograph', '100m water resistance', 'Sapphire crystal'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Black', 'black', 'steel', 'steel', '#ffffff')] },
  { b: 'Longines', m: 'Spirit Zulu Time', ref: '', cat: 'swiss', s: 'diver', p: 320000, mrp: 320000, st: 'metal', size: '42 mm', wr: '100m', mv: 'Automatic GMT Chronometer', glass: 'Sapphire Crystal', pop: 6, ind: 'arabic', date: true, gmt: true,
    blurb: "A certified chronometer GMT for travellers, with a 24-hour ceramic bezel. (Approx. price)",
    feats: ['GMT function', 'Certified chronometer', 'Ceramic bezel'],
    v: [V('Black', 'black', 'steel', 'steel', '#ffffff'), V('Blue', 'blue', 'steel', 'steel', '#ffffff')] },
  { b: 'Longines', m: 'DolceVita Women', ref: '', cat: 'swiss', s: 'dress', p: 150000, mrp: 150000, st: 'metal', size: '23.3 × 37 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 6, ind: 'roman', small: true, women: true, sq: true,
    blurb: "Longines DolceVita - sweet life, Italian-inspired elegance. (Approx. price)",
    feats: ['Rectangular case', 'Roman numerals', 'Sapphire crystal'],
    v: [V('Silver', 'silver', 'steel', 'steel', '#1d1d1f')] },
  { b: 'Rado', m: 'Coupole Classic', ref: '', cat: 'swiss', s: 'dress', p: 110000, mrp: 110000, st: 'metal', size: '38 mm', wr: '50m', mv: 'Automatic', glass: 'Sapphire Crystal', pop: 6, ind: 'stick', date: true, auto: true,
    blurb: "A slim, curved classic from Rado with an elegant domed crystal. (Approx. price)",
    feats: ['Automatic movement', 'Sapphire crystal', 'Steel bracelet'],
    v: [V('Silver', 'silver', 'steel', 'steel', '#1d1d1f'), V('Black', 'black', 'steel', 'steel', '#ffffff')] },
  { b: 'Rado', m: 'DiaMaster', ref: '', cat: 'swiss', s: 'dress', p: 150000, mrp: 150000, st: 'metal', size: '41 mm', wr: '100m', mv: 'Automatic', glass: 'Sapphire Crystal', pop: 5, ind: 'stick', date: true, auto: true,
    blurb: "Rado DiaMaster - a ceramos case with a soft, matte finish. (Approx. price)",
    feats: ['Ceramos case', 'Automatic movement', 'Sapphire crystal'],
    v: [V('Grey', 'grey', '#7d7f84', '#7d7f84', '#ffffff', '#7d7f84')] },
  { b: 'Rado', m: 'Florence Women', ref: '', cat: 'swiss', s: 'dress', p: 95000, mrp: 95000, st: 'metal', size: '30 mm', wr: '50m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 6, ind: 'dots', small: true, women: true,
    blurb: "A feminine Rado with a mother-of-pearl dial and diamond markers. (Approx. price)",
    feats: ['Mother-of-pearl dial', 'Diamond markers', 'Sapphire crystal'],
    v: [V('MOP / Rose Gold', 'mop', 'rose', 'rose', '#6b3a2e', '#d9937f'), V('White / Steel', 'white', 'steel', 'steel', '#1d1d1f')] },
  { b: 'Rado', m: 'Centrix Chronograph', ref: '', cat: 'swiss', s: 'chrono', p: 170000, mrp: 170000, st: 'metal', size: '42 mm', wr: '100m', mv: 'Swiss Chronograph', glass: 'Sapphire Crystal', pop: 5, ind: 'stick', date: true,
    blurb: "A sporty chronograph version of the Rado Centrix. (Approx. price)",
    feats: ['Chronograph', 'Ceramic & steel bracelet', 'Sapphire crystal'],
    v: [V('Black', 'black', 'steel', 'steel', '#e03131')] },
  { b: 'Frederique Constant', m: 'Classics Index Automatic', ref: '', cat: 'swiss', s: 'dress', p: 135000, mrp: 135000, st: 'leather', size: '40 mm', wr: '50m', mv: 'Automatic', glass: 'Sapphire Crystal', pop: 6, ind: 'stick', dn: 'F.CONSTANT', date: true, auto: true,
    blurb: "A refined Swiss automatic dress watch at a sensible price. (Approx. price)",
    feats: ['Automatic movement', 'Sapphire crystal', 'Leather strap'],
    v: [V('Navy', 'navy', 'steel', 'navy', '#ffffff', '#15213b'), V('Silver', 'silver', 'gold', 'brown', '#3a2a05', '#dcdde0')] },
  { b: 'Frederique Constant', m: 'Highlife Automatic', ref: '', cat: 'swiss', s: 'dress', p: 210000, mrp: 210000, st: 'metal', size: '41 mm', wr: '100m', mv: 'Automatic', glass: 'Sapphire Crystal', pop: 5, ind: 'stick', dn: 'F.CONSTANT', date: true, auto: true,
    blurb: "A modern integrated-bracelet sports watch with a globe-pattern dial. (Approx. price)",
    feats: ['Integrated bracelet', 'Automatic movement', '100m water resistance'],
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Green', 'green', 'steel', 'steel', '#ffffff')] },
  { b: 'Movado', m: 'Bold Evolution Chronograph', ref: '', cat: 'swiss', s: 'chrono', p: 85000, mrp: 85000, st: 'metal', size: '42 mm', wr: '30m', mv: 'Swiss Chronograph Quartz', glass: 'Sapphire Crystal', pop: 6, ind: 'museum',
    blurb: "A bold, modern take on the Museum dial with chronograph sub-dials. (Approx. price)",
    feats: ['Chronograph', 'Museum dot at 12', 'Steel bracelet'],
    v: [V('Black', 'black', 'gun', 'gun', '#c9ccd1', '#4a4d52'), V('Blue', 'navy', 'steel', 'steel', '#ffffff', '#15213b')] },
  { b: 'Xylys', m: 'Ceramic Women', ref: '', cat: 'xylys', s: 'dress', p: 20000, mrp: 20000, st: 'metal', size: '32 mm', wr: '30m', mv: 'Swiss Quartz', glass: 'Sapphire Crystal', pop: 6, ind: 'dots', small: true, women: true,
    blurb: "A light, glossy ceramic Xylys for her. (Approx. price)",
    feats: ['Ceramic bracelet', 'Swiss made', 'Sapphire crystal'],
    v: [V('White', 'white', '#f1f1f1', '#f1f1f1', '#d4af37'), V('Black', 'black', 'ceramic', 'ceramic', '#d4af37', '#1a1a1c')] },
  { b: 'Hugo Boss', m: 'Champion Chronograph', ref: '', cat: 'designer', s: 'chrono', p: 23000, mrp: 23000, st: 'leather', size: '44 mm', wr: '50m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 6, ind: 'arabic', dn: 'BOSS',
    blurb: "Bold numerals and a chronograph layout on a leather strap. (Approx. price)",
    feats: ['Chronograph', 'Leather strap'],
    v: [V('Black / Brown', 'black', 'steel', 'brown', '#e03131', '#6b4226')] },
  { b: 'Armani Exchange', m: 'Cayde Slim', ref: '', cat: 'designer', s: 'dress', p: 12995, mrp: 12995, st: 'mesh', size: '42 mm', wr: '50m', mv: 'Quartz', glass: 'Mineral Glass', pop: 6, ind: 'stick', dn: 'A|X', date: true,
    blurb: "A clean, slim A|X watch on a mesh bracelet. (Approx. price)",
    feats: ['Mesh bracelet', 'Slim case', 'Date window'],
    v: [V('Black', 'black', 'gun', 'gun', '#c9ccd1', '#4a4d52'), V('Blue', 'navy', 'steel', 'steel', '#ffffff', '#15213b')] },
  { b: 'Michael Kors', m: 'Bradshaw Chronograph', ref: '', cat: 'designer', s: 'chrono', p: 27995, mrp: 27995, st: 'metal', size: '43 mm', wr: '100m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 6, ind: 'stick', date: true,
    blurb: "An oversized Bradshaw chronograph - bold, glamorous and unisex. (Approx. price)",
    feats: ['Chronograph', 'Oversized case', '100m water resistance'],
    v: [V('Rose Gold', 'pink', 'rose', 'rose', '#6b3a2e', '#d9937f'), V('Gold', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37')] },
  { b: 'Tommy Hilfiger', m: 'Women Multifunction', ref: '', cat: 'designer', s: 'chrono', p: 13999, mrp: 13999, st: 'metal', size: '38 mm', wr: '30m', mv: 'Quartz Multifunction', glass: 'Mineral Glass', pop: 6, ind: 'dots', dn: 'TOMMY', small: true, women: true,
    blurb: "A sparkling multifunction Tommy watch for her. (Approx. price)",
    feats: ['Multifunction sub-dials', 'Crystal markers', 'Steel bracelet'],
    v: [V('Rose Gold', 'pink', 'rose', 'rose', '#6b3a2e', '#d9937f'), V('Silver', 'white', 'steel', 'steel', '#1d1d1f')] },
  { b: 'Lacoste', m: '12.12 Women', ref: '', cat: 'designer', s: 'dress', p: 9999, mrp: 9999, st: 'rubber', size: '36 mm', wr: '50m', mv: 'Quartz', glass: 'Mineral Glass', pop: 6, ind: 'arabic', small: true, women: true,
    blurb: "Inspired by the iconic polo shirt - sporty, colourful and casual. (Approx. price)",
    feats: ['Silicone strap', 'Polo-inspired design'],
    v: [V('White', 'white', 'white', 'white', '#1f4d3a'), V('Navy', 'navy', 'navy', 'navy', '#ffffff', '#15213b')] },
  { b: 'Kate Spade', m: 'Metro Women', ref: '', cat: 'designer', s: 'dress', p: 14995, mrp: 14995, st: 'mesh', size: '34 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 5, ind: 'stick', small: true, women: true,
    blurb: "A chic, minimal Kate Spade watch on a mesh bracelet. (Approx. price)",
    feats: ['Mesh bracelet', 'Minimal dial'],
    v: [V('Gold', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37')] },
];
