/* Starter catalogue: popular, top-selling watch models in India (prices in ₹).
 * Prices are typical market prices - adjust them to your own selling prices.
 *
 * Variant helper V(name, dial, case, strap, accent, swatch)
 * Each colour is a token from TOKENS below or a #hex value.
 */
const TOKENS = {
  black: '#151515', jet: '#0b0b0b', white: '#f4f3ef', silver: '#dcdde0', blue: '#1d4f8c', navy: '#15213b',
  green: '#1f4d3a', olive: '#4b5a2e', gold: '#d4af37', rose: '#d9937f', champagne: '#ecd9aa', brown: '#6b4226',
  tan: '#a8703d', red: '#a3161f', grey: '#5a5d63', pink: '#f4b6c2', purple: '#7d6bd6', teal: '#0f6e6e',
  orange: '#ff6b1a', cream: '#f1e8d2', steel: '#c9ccd1', gun: '#4a4d52', sky: '#8ccdf5', lime: '#b5e61d',
  yellow: '#f5c518', mint: '#a6e8cf', coral: '#ff7f6a', choc: '#3d2a1e', ivory: '#fbf7ec', lavender: '#c8b8f0',
  resin: '#1b1b1b', beige: '#d9c7a3', wine: '#6d1a2a', mblue: '#2a6fdb', dgreen: '#123a2c',
};
const t = (c) => (c && c[0] !== '#' ? TOKENS[c] || c : c);
function V(name, dial, kase, strap, accent, swatch) {
  return { name, dial: t(dial), case: t(kase), strap: t(strap), accent: t(accent || '#e03131'), swatch: t(swatch || dial) };
}

// style: dress | field | diver | chrono | retro | gsquare | goak | gbig | sportdigital | smartsq | smartrd | band | kidsana
// strap: leather | metal | jubilee | mesh | rubber | resin | fabric | nato
module.exports = [
  // ---------------- CASIO G-SHOCK / SPORTS ----------------
  { b: 'Casio', m: 'G-Shock GA-2100 "CasiOak"', ref: 'GA-2100-1A1', cat: 'sports', s: 'goak', p: 9995, mrp: 10995, st: 'resin', size: '48.5 × 45.4 mm', wr: '200m', mv: 'Quartz Analog-Digital', glass: 'Mineral Glass', pop: 10,
    blurb: 'The iconic octagonal G-Shock that everyone wants - ultra-slim Carbon Core Guard case, analog-digital display and legendary G-Shock toughness.',
    feats: ['Carbon Core Guard structure', 'Shock resistant', 'World time (48 cities)', '1/100-sec stopwatch', 'Double LED light', '3-year battery'],
    v: [V('All Black', 'jet', 'resin', 'resin', '#8a8a8a'), V('Black & Red', 'black', 'resin', 'resin', '#e03131', '#e03131'), V('Arctic White', 'white', 'white', 'white', '#1d1d1f'), V('Navy Blue', 'navy', '#1f2f55', '#1f2f55', '#f5c518'), V('Olive Green', 'olive', '#4b5a2e', '#4b5a2e', '#f5c518')] },
  { b: 'Casio', m: 'G-Shock DW-5600E', ref: 'DW-5600E-1V', cat: 'sports', s: 'gsquare', p: 7995, mrp: 8495, st: 'resin', size: '48.9 × 42.8 mm', wr: '200m', mv: 'Digital Quartz', glass: 'Mineral Glass', pop: 10,
    blurb: 'The original square G-Shock - a true legend since 1983. Tough, reliable and instantly recognisable.',
    feats: ['Shock resistant', '1/100-sec stopwatch', 'Countdown timer', 'Daily alarm', 'EL backlight', 'Full auto-calendar'],
    v: [V('Classic Black', 'black', 'resin', 'resin', '#e03131'), V('Stealth Black', 'jet', '#111111', '#111111', '#777777'), V('White', 'white', 'white', 'white', '#1d4f8c'), V('Camo Olive', 'olive', '#4b5a2e', '#4b5a2e', '#f5c518')] },
  { b: 'Casio', m: 'G-Shock GA-110', ref: 'GA-110-1B', cat: 'sports', s: 'gbig', p: 11995, mrp: 12995, st: 'resin', size: '55 × 51.2 mm', wr: '200m', mv: 'Quartz Analog-Digital', glass: 'Mineral Glass', pop: 9,
    blurb: 'Big, bold and built for adventure - the GA-110 is one of the best-selling G-Shocks ever made, with a large 3D dial and magnetic resistance.',
    feats: ['Shock & magnetic resistant', 'World time', '1/1000-sec stopwatch', '5 daily alarms', 'LED light', 'Speed indicator'],
    v: [V('Black Silver', 'black', 'resin', 'resin', '#c9ccd1'), V('All Black', 'jet', '#111111', '#111111', '#555555'), V('Black Red', 'black', 'resin', 'resin', '#e03131', '#e03131'), V('Black Gold', 'black', 'resin', 'resin', '#d4af37', '#d4af37')] },
  { b: 'Casio', m: 'G-Shock GA-700', ref: 'GA-700-1B', cat: 'sports', s: 'gbig', p: 10995, mrp: 11495, st: 'resin', size: '57.5 × 53.4 mm', wr: '200m', mv: 'Quartz Analog-Digital', glass: 'Mineral Glass', pop: 7,
    blurb: 'A large, easy-to-read G-Shock with a front-facing button for the super-bright LED light. Made for tough jobs and outdoor life.',
    feats: ['Shock resistant', 'Front button LED light', 'World time', 'Stopwatch & timer', '5 alarms'],
    v: [V('Black', 'black', 'resin', 'resin', '#c9ccd1'), V('Military Green', 'olive', '#4b5a2e', '#4b5a2e', '#f5c518'), V('Red', 'black', '#a3161f', '#a3161f', '#ffffff', '#a3161f')] },
  { b: 'Casio', m: 'G-Shock DW-5900', ref: 'DW-5900-1', cat: 'sports', s: 'gsquare', p: 9495, mrp: 9995, st: 'resin', size: '48.7 × 46.8 mm', wr: '200m', mv: 'Digital Quartz', glass: 'Mineral Glass', pop: 6,
    blurb: 'The 1987 "three-eye" G-Shock reborn - a retro-cool digital with a three-segment display.',
    feats: ['Shock resistant', 'Three-eye display', 'Stopwatch', 'Countdown timer', 'LED backlight'],
    v: [V('Black', 'black', 'resin', 'resin', '#e03131'), V('Black & Yellow', 'black', 'resin', 'resin', '#f5c518', '#f5c518')] },
  { b: 'Casio', m: 'Baby-G BA-110', ref: 'BA-110-7A3', cat: 'women', s: 'gbig', p: 9995, mrp: 10995, st: 'resin', size: '46.3 × 43.4 mm', wr: '100m', mv: 'Quartz Analog-Digital', glass: 'Mineral Glass', pop: 7,
    blurb: 'Tough and trendy - Baby-G brings G-Shock toughness in a sporty, colourful design made for her.',
    feats: ['Shock resistant', 'World time', 'Stopwatch', '5 alarms', 'LED light'],
    v: [V('White', 'white', 'white', 'white', '#d4af37'), V('Pastel Pink', 'pink', '#f4b6c2', '#f4b6c2', '#8a3b52'), V('Sky Blue', 'sky', '#8ccdf5', '#8ccdf5', '#0b4f7c'), V('Black Rose Gold', 'black', 'resin', 'resin', '#d9937f', '#d9937f')] },

  // ---------------- CASIO VINTAGE / COLLECTION ----------------
  { b: 'Casio', m: 'Vintage A168WA', ref: 'A168WA-1', cat: 'men', s: 'retro', p: 3295, mrp: 3495, st: 'metal', size: '38.6 × 36.3 mm', wr: 'Water Resistant', mv: 'Digital Quartz', glass: 'Resin Glass', pop: 10,
    blurb: 'The classic Casio vintage digital with Illuminator light - a retro style icon that never goes out of fashion.',
    feats: ['Illuminator LED light', 'Daily alarm & hourly chime', '1/100-sec stopwatch', 'Auto calendar', '12/24-hour format'],
    labels: { top: 'CASIO', tr: 'ILLUMINATOR', bottom: 'ALARM CHRONOGRAPH' },
    v: [V('Silver', 'black', 'steel', 'steel', '#3aa0ff', '#c9ccd1'), V('Gold', 'black', 'gold', 'gold', '#d4af37', '#d4af37'), V('Black', 'black', '#2b2b2b', '#2b2b2b', '#3aa0ff', '#2b2b2b')] },
  { b: 'Casio', m: 'Vintage A158WA', ref: 'A158WA-1', cat: 'men', s: 'retro', p: 2295, mrp: 2495, st: 'metal', size: '36.8 × 33.2 mm', wr: 'Water Resistant', mv: 'Digital Quartz', glass: 'Resin Glass', pop: 9,
    blurb: 'Slim, lightweight and timeless - the A158 is the everyday Casio retro watch loved worldwide.',
    feats: ['LED light', 'Daily alarm', 'Stopwatch', 'Auto calendar', '7-year battery'],
    labels: { top: 'CASIO', tr: 'WATER RESIST', bottom: 'ALARM CHRONOGRAPH' },
    v: [V('Silver', 'black', 'steel', 'steel', '#ffffff', '#c9ccd1'), V('Gold', 'black', 'gold', 'gold', '#d4af37', '#d4af37')] },
  { b: 'Casio', m: 'F-91W Classic', ref: 'F-91W-1', cat: 'sports', s: 'retro', p: 1195, mrp: 1295, st: 'resin', size: '38.2 × 35.2 mm', wr: 'Water Resistant', mv: 'Digital Quartz', glass: 'Resin Glass', pop: 10,
    blurb: 'Possibly the most famous digital watch in the world - light, accurate and with a 7-year battery.',
    feats: ['7-year battery', 'Daily alarm', 'Stopwatch', 'Auto calendar', 'LED light'],
    labels: { top: 'CASIO', tr: 'F-91W', bottom: 'LIGHT  ALARM CHRONOGRAPH', resin: true },
    v: [V('Classic Black', 'black', 'resin', 'resin', '#3a7bd5'), V('Black Gold', 'black', 'resin', 'resin', '#d4af37', '#d4af37')] },
  { b: 'Casio', m: 'Vintage A700W', ref: 'A700W-1A', cat: 'men', s: 'retro', p: 3995, mrp: 4295, st: 'mesh', size: '36.1 × 34.4 mm', wr: 'Water Resistant', mv: 'Digital Quartz', glass: 'Resin Glass', pop: 7,
    blurb: 'Ultra-slim vintage Casio with a sleek mesh bracelet - a modern classic for minimalists.',
    feats: ['Slim 8.2mm case', 'LED light', 'Alarm', 'Stopwatch', '10-year battery'],
    labels: { top: 'CASIO', tr: 'LED LIGHT', bottom: 'ALARM CHRONOGRAPH' },
    v: [V('Silver Mesh', 'black', 'steel', 'steel', '#ffffff', '#c9ccd1'), V('Gold Mesh', 'black', 'gold', 'gold', '#d4af37', '#d4af37')] },
  { b: 'Casio', m: 'Youth W-218H', ref: 'W-218H-1A', cat: 'sports', s: 'sportdigital', p: 1795, mrp: 1895, st: 'resin', size: '44.2 × 43 mm', wr: '50m', mv: 'Digital Quartz', glass: 'Resin Glass', pop: 8,
    blurb: 'A clean, sporty digital watch with a big display - light on the wrist and easy on the pocket.',
    feats: ['Large display', 'Stopwatch', 'Daily alarm', 'LED light', '7-year battery'],
    v: [V('Black', 'black', 'resin', 'resin', '#e03131'), V('Navy', 'navy', '#1f2f55', '#1f2f55', '#f5c518'), V('Khaki Green', 'olive', '#4b5a2e', '#4b5a2e', '#f5c518')] },
  { b: 'Casio', m: 'Youth W-800H', ref: 'W-800H-1A', cat: 'sports', s: 'sportdigital', p: 1895, mrp: 1995, st: 'resin', size: '44.4 × 36.8 mm', wr: '100m', mv: 'Digital Quartz', glass: 'Resin Glass', pop: 8,
    blurb: 'A rugged, 100-metre water-resistant sports digital with vibration alarm - perfect for gym, swimming and school.',
    feats: ['100m water resistance', 'Vibration alarm', 'Dual time', 'Stopwatch', 'LED light'],
    v: [V('Black', 'black', 'resin', 'resin', '#3a7bd5'), V('Black Blue', 'black', 'resin', 'resin', '#2a6fdb', '#2a6fdb')] },
  { b: 'Casio', m: 'Royale AE-1200WH', ref: 'AE-1200WH-1A', cat: 'sports', s: 'sportdigital', p: 3495, mrp: 3695, st: 'resin', size: '45 × 42.1 mm', wr: '100m', mv: 'Digital Quartz', glass: 'Resin Glass', pop: 9,
    blurb: 'Nicknamed the "Casio Royale", this world-time digital is famous for its cool map display and 10-year battery.',
    feats: ['World time with map', '10-year battery', '5 alarms', 'Stopwatch & timer', 'LED light'],
    v: [V('Black', 'black', 'resin', 'resin', '#e03131'), V('Steel Bracelet', 'black', 'steel', 'steel', '#e03131', '#c9ccd1')] },
  { b: 'Casio', m: 'MQ-24 Classic', ref: 'MQ-24-7B', cat: 'men', s: 'dress', p: 1195, mrp: 1295, st: 'resin', size: '38.8 × 34.9 mm', wr: 'Water Resistant', mv: 'Quartz', glass: 'Resin Glass', pop: 8,
    blurb: 'Simple, light and super reliable - the MQ-24 is the classic everyday analog watch at an unbeatable price.',
    feats: ['Lightweight resin case', 'Easy-read dial', 'Long battery life'], ind: 'arabic',
    v: [V('White Dial', 'white', '#1b1b1b', '#1b1b1b', '#e03131'), V('Black Dial', 'black', '#1b1b1b', '#1b1b1b', '#e03131')] },
  { b: 'Casio', m: 'Enticer MTP-1302D', ref: 'MTP-1302D-1A1', cat: 'men', s: 'dress', p: 3695, mrp: 3995, st: 'metal', size: '38.5 mm', wr: '50m', mv: 'Quartz', glass: 'Mineral Glass', pop: 8,
    blurb: 'A smart, classic steel watch with a clean dial and date window - the perfect office watch.',
    feats: ['Stainless steel bracelet', 'Date display', 'Luminous hands'], ind: 'stick', date: true,
    v: [V('Black Dial', 'black', 'steel', 'steel', '#c9ccd1'), V('White Dial', 'white', 'steel', 'steel', '#1d1d1f'), V('Blue Dial', 'blue', 'steel', 'steel', '#ffffff')] },
  { b: 'Casio', m: 'Enticer MTP-VD01', ref: 'MTP-VD01D-1B', cat: 'men', s: 'dress', p: 2995, mrp: 3195, st: 'metal', size: '45 mm', wr: '50m', mv: 'Quartz', glass: 'Mineral Glass', pop: 8,
    blurb: 'Bold 45mm face, clean dial and steel bracelet - a big-looking watch at a small price.',
    feats: ['Large 45mm case', 'Stainless steel', 'Date display'], ind: 'stick', date: true,
    v: [V('Black Dial', 'black', 'steel', 'steel', '#c9ccd1'), V('Blue Dial', 'blue', 'steel', 'steel', '#ffffff'), V('Green Dial', 'green', 'steel', 'steel', '#ffffff')] },
  { b: 'Casio', m: 'Enticer MTP-1374D Multifunction', ref: 'MTP-1374D-1A', cat: 'men', s: 'chrono', p: 6995, mrp: 7495, st: 'metal', size: '43.5 mm', wr: '50m', mv: 'Quartz Multifunction', glass: 'Mineral Glass', pop: 8,
    blurb: 'A sharp multifunction dress watch with day, date and 24-hour sub-dials on a solid steel bracelet.',
    feats: ['Day, date & 24-hour sub-dials', 'Stainless steel bracelet', 'Luminous hands'], ind: 'stick',
    v: [V('Black Dial', 'black', 'steel', 'steel', '#c9ccd1'), V('Blue Dial', 'blue', 'steel', 'steel', '#ffffff'), V('White Dial', 'white', 'steel', 'steel', '#1d1d1f')] },
  { b: 'Casio', m: 'Duro MDV-106 Diver', ref: 'MDV-106-1A', cat: 'men', s: 'diver', p: 8995, mrp: 9495, st: 'resin', size: '44.2 mm', wr: '200m', mv: 'Quartz', glass: 'Mineral Glass', pop: 9,
    blurb: 'The famous "Casio Duro" 200m diver - rotating bezel, luminous markers and a price that beats watches costing 10× more.',
    feats: ['200m dive rating', 'Rotating diver bezel', 'Date display', 'Luminous hands & markers', 'Screw-lock crown'], ind: 'dots', date: true,
    v: [V('Black', 'black', 'steel', 'resin', '#e03131', '#151515'), V('Blue', 'navy', 'steel', 'navy', '#ffffff', '#15213b'), V('Green', 'dgreen', 'steel', 'dgreen', '#d4af37', '#123a2c')] },
  { b: 'Casio', m: 'Edifice EFR-526D Chronograph', ref: 'EFR-526D-1AV', cat: 'chrono', s: 'chrono', p: 11995, mrp: 12995, st: 'metal', size: '43.8 mm', wr: '100m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 8,
    blurb: 'Inspired by motorsport, the Edifice EFR-526 is a sporty steel chronograph with a tachymeter bezel.',
    feats: ['1/20-sec chronograph', 'Tachymeter bezel', 'Date display', '100m water resistance'], ind: 'stick', tachy: true, date: true,
    v: [V('Black Dial', 'black', 'steel', 'steel', '#e03131'), V('Blue Dial', 'blue', 'steel', 'steel', '#ffffff'), V('White Dial', 'white', 'steel', 'steel', '#1d1d1f')] },
  { b: 'Casio', m: 'Edifice EFV-540D Chronograph', ref: 'EFV-540D-1AV', cat: 'chrono', s: 'chrono', p: 12495, mrp: 12995, st: 'metal', size: '47.1 mm', wr: '100m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 7,
    blurb: 'Large, bold and dynamic - a racing-inspired chronograph with a sharp bezel and steel bracelet.',
    feats: ['Chronograph', 'Date display', 'Rotating bezel', '100m water resistance'], ind: 'stick', tachy: true, date: true,
    v: [V('Black Dial', 'black', 'steel', 'steel', '#e03131'), V('Blue Dial', 'blue', 'steel', 'steel', '#f5c518')] },
  { b: 'Casio', m: 'Edifice EQS-940 Solar', ref: 'EQS-940DB-1AV', cat: 'chrono', s: 'chrono', p: 13995, mrp: 14995, st: 'metal', size: '45 mm', wr: '100m', mv: 'Solar Chronograph', glass: 'Mineral Glass', pop: 6,
    blurb: 'Solar powered - never needs a battery change. A premium Edifice chronograph with a sporty, sharp look.',
    feats: ['Tough Solar (no battery change)', 'Chronograph', 'Date display', 'Battery level indicator'], ind: 'stick', date: true,
    v: [V('Black Dial', 'black', 'steel', 'steel', '#e03131'), V('Blue Dial', 'blue', 'steel', 'steel', '#ffffff'), V('Black IP', 'black', '#2b2b2b', '#2b2b2b', '#d4af37', '#2b2b2b')] },
  { b: 'Casio', m: 'Vintage LA670WA', ref: 'LA670WA-1', cat: 'women', s: 'retro', p: 3295, mrp: 3495, st: 'metal', size: '30.2 × 24.6 mm', wr: 'Water Resistant', mv: 'Digital Quartz', glass: 'Resin Glass', pop: 8, small: true,
    blurb: 'A petite vintage digital for her - retro charm on a slim steel bracelet.',
    feats: ['LED light', 'Daily alarm', 'Stopwatch', 'Auto calendar'],
    labels: { top: 'CASIO', tr: 'LIGHT', bottom: 'ALARM CHRONOGRAPH' },
    v: [V('Silver', 'black', 'steel', 'steel', '#ffffff', '#c9ccd1'), V('Gold', 'black', 'gold', 'gold', '#d4af37', '#d4af37'), V('Rose Gold', 'black', 'rose', 'rose', '#d9937f', '#d9937f')] },
  { b: 'Casio', m: 'LTP-V005 Women', ref: 'LTP-V005D-7B', cat: 'women', s: 'dress', p: 2195, mrp: 2395, st: 'metal', size: '30 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 7, small: true,
    blurb: 'Elegant and simple - a slim everyday steel watch for women.',
    feats: ['Slim steel bracelet', 'Easy-read dial'], ind: 'stick',
    v: [V('White Dial', 'white', 'steel', 'steel', '#1d1d1f'), V('Gold Tone', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37'), V('Rose Gold', 'ivory', 'rose', 'rose', '#6b3a2e', '#d9937f')] },
  { b: 'Casio', m: 'Youth LW-200 Kids', ref: 'LW-200-1B', cat: 'kids', s: 'sportdigital', p: 1795, mrp: 1895, st: 'resin', size: '43 mm', wr: '100m', mv: 'Digital Quartz', glass: 'Resin Glass', pop: 7, small: true,
    blurb: 'Light, tough and swim-proof - a perfect first digital watch for school and sports.',
    feats: ['100m water resistance', '10-year battery', 'Alarm', 'Stopwatch', 'LED light'],
    v: [V('Black', 'black', 'resin', 'resin', '#e03131'), V('Blue', 'black', '#2a6fdb', '#2a6fdb', '#f5c518', '#2a6fdb'), V('Pink', 'black', '#f48fb1', '#f48fb1', '#ffffff', '#f48fb1')] },

  // ---------------- TITAN ----------------
  { b: 'Titan', m: 'Neo Analog', ref: 'NS1805SL01', cat: 'men', s: 'dress', p: 5495, mrp: 5995, st: 'leather', size: '42 mm', wr: '50m', mv: 'Quartz', glass: 'Mineral Glass', pop: 9,
    blurb: 'Titan Neo - clean, modern and versatile. A best-selling Titan that looks great from office to evening.',
    feats: ['Genuine leather strap', 'Day & date display', 'Stainless steel back'], ind: 'stick', date: true,
    v: [V('Blue / Brown', 'blue', 'steel', 'brown', '#ffffff', '#1d4f8c'), V('Black / Black', 'black', 'steel', 'black', '#c9ccd1'), V('White / Tan', 'white', 'rose', 'tan', '#1d1d1f', '#a8703d')] },
  { b: 'Titan', m: 'Karishma Analog', ref: 'NR1580SM04', cat: 'men', s: 'dress', p: 2995, mrp: 3195, st: 'metal', size: '38 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 10,
    blurb: "India's most loved everyday Titan - trusted quality, classic looks and a steel bracelet, at a great price.",
    feats: ['Stainless steel bracelet', 'Day & date', 'Trusted Titan quality'], ind: 'roman', date: true,
    v: [V('White Dial', 'white', 'steel', 'steel', '#1d1d1f'), V('Black Dial', 'black', 'steel', 'steel', '#d4af37'), V('Gold Tone', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37'), V('Blue Dial', 'blue', 'steel', 'steel', '#ffffff')] },
  { b: 'Titan', m: 'Octane Chronograph', ref: '90102KM01', cat: 'chrono', s: 'chrono', p: 8995, mrp: 9495, st: 'metal', size: '45 mm', wr: '100m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 8,
    blurb: 'Titan Octane - sporty, masculine and loaded with function. A bold chronograph for the go-getter.',
    feats: ['Working chronograph', 'Date display', 'Tachymeter scale', '100m water resistance'], ind: 'stick', tachy: true, date: true,
    v: [V('Black Dial', 'black', 'steel', 'steel', '#ff6b1a'), V('Blue Dial', 'blue', 'steel', 'steel', '#ffffff'), V('Gunmetal', 'black', 'gun', 'gun', '#ff6b1a', '#4a4d52')] },
  { b: 'Titan', m: 'Workwear', ref: '1802NM01', cat: 'men', s: 'dress', p: 5495, mrp: 5795, st: 'metal', size: '41 mm', wr: '50m', mv: 'Quartz', glass: 'Mineral Glass', pop: 7,
    blurb: 'Designed for the modern workplace - a sharp, textured dial with day-date on a sleek steel bracelet.',
    feats: ['Day & date', 'Textured dial', 'Stainless steel'], ind: 'stick', date: true,
    v: [V('Blue Dial', 'blue', 'steel', 'steel', '#ffffff'), V('Grey Dial', 'grey', 'steel', 'steel', '#ffffff'), V('Green Dial', 'green', 'steel', 'steel', '#d4af37')] },
  { b: 'Titan', m: 'Regalia Gold', ref: '1825YM01', cat: 'premium', s: 'dress', p: 9995, mrp: 10995, st: 'metal', size: '42 mm', wr: '50m', mv: 'Quartz', glass: 'Mineral Glass', pop: 7,
    blurb: 'Regal, rich and sophisticated - Titan Regalia in a gold finish is made for special moments and celebrations.',
    feats: ['Gold-plated case & bracelet', 'Day & date', 'Gift-ready premium box'], ind: 'roman', date: true,
    v: [V('Champagne Gold', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37'), V('Black Gold', 'black', 'gold', 'gold', '#d4af37', '#151515'), V('Two-Tone', 'white', 'gold', 'steel', '#3a2a05', '#dcdde0')] },
  { b: 'Titan', m: 'Edge Baseline Ultra-Slim', ref: '1843QL01', cat: 'premium', s: 'dress', p: 13995, mrp: 14995, st: 'leather', size: '40 mm', wr: '30m', mv: 'Slim Quartz', glass: 'Sapphire Crystal', pop: 6,
    blurb: "From the makers of one of the world's slimmest watches - Titan Edge is minimal, elegant and incredibly thin.",
    feats: ['Ultra-slim case', 'Sapphire crystal', 'Genuine leather strap', 'Minimal dial'], ind: 'stick',
    v: [V('Black', 'black', 'steel', 'black', '#c9ccd1'), V('White / Brown', 'white', 'steel', 'brown', '#1d1d1f', '#6b4226'), V('Blue / Navy', 'navy', 'steel', 'navy', '#ffffff')] },
  { b: 'Titan', m: 'Raga Viva Women', ref: '95117YM01', cat: 'women', s: 'dress', p: 9495, mrp: 9995, st: 'jubilee', size: '28 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 8, small: true,
    blurb: 'Titan Raga - jewellery for the wrist. A graceful, bracelet-style watch for every celebration.',
    feats: ['Bracelet-style design', 'Mother-of-pearl dial', 'Crystal accents', 'Gift-ready box'], ind: 'dots',
    v: [V('Gold', 'ivory', 'gold', 'gold', '#d4af37', '#d4af37'), V('Rose Gold', '#f6e3dc', 'rose', 'rose', '#6b3a2e', '#d9937f'), V('Silver', 'ivory', 'steel', 'steel', '#1d1d1f', '#dcdde0')] },
  { b: 'Titan', m: 'Karishma Women', ref: 'NR2593SM01', cat: 'women', s: 'dress', p: 2495, mrp: 2695, st: 'metal', size: '26 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 9, small: true,
    blurb: 'Classic, dependable and elegant - Titan Karishma for women is a gift that never disappoints.',
    feats: ['Stainless steel bracelet', 'Easy-read dial', 'Trusted Titan quality'], ind: 'stick',
    v: [V('White Dial', 'white', 'steel', 'steel', '#1d1d1f'), V('Gold Tone', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37'), V('Rose Gold', 'ivory', 'rose', 'rose', '#6b3a2e', '#d9937f')] },
  { b: 'Titan', m: 'Purple Glam Women', ref: '95143WL01', cat: 'women', s: 'dress', p: 6995, mrp: 7495, st: 'leather', size: '32 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 6, small: true,
    blurb: 'Bold, fun and fashionable - Titan Purple adds a statement touch to your everyday look.',
    feats: ['Leather strap', 'Crystal-studded markers', 'Fashion-forward design'], ind: 'dots',
    v: [V('Blush Pink', 'pink', 'rose', 'pink', '#8a3b52'), V('Lavender', 'lavender', 'steel', 'purple', '#3d2c8d'), V('Classic Black', 'black', 'rose', 'black', '#d9937f')] },
  { b: 'Titan', m: 'Smart 3 AMOLED', ref: '90182AP01', cat: 'smart', s: 'smartsq', p: 6995, mrp: 9995, st: 'rubber', size: '1.96" AMOLED', wr: 'IP68', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 7,
    blurb: 'Titan Smart 3 with a big AMOLED display, Bluetooth calling and 100+ sports modes, from India\'s most trusted watch brand.',
    feats: ['1.96" AMOLED display', 'Bluetooth calling', 'SpO2 & heart-rate', '100+ sports modes', 'Up to 7 days battery'],
    v: [V('Black', 'black', 'gun', 'black', '#2a6fdb'), V('Blue', 'navy', 'steel', 'navy', '#8ccdf5', '#15213b'), V('Rose Gold', 'black', 'rose', 'pink', '#ff7f6a', '#d9937f')] },
  { b: 'Titan', m: 'Zoop Kids Analog', ref: 'C3025PP01', cat: 'kids', s: 'kidsana', p: 1195, mrp: 1295, st: 'rubber', size: '34 mm', wr: '50m', mv: 'Quartz', glass: 'Acrylic', pop: 8, small: true,
    blurb: 'Titan Zoop - bright, fun and easy to read. Helps kids learn to tell the time.',
    feats: ['Kid-friendly dial', 'Soft silicone strap', 'Durable build'], ind: 'arabic',
    v: [V('Sky Blue', '#e6f5ff', '#2a6fdb', 'sky', '#2a6fdb', '#8ccdf5'), V('Pink', '#fff0f5', '#f48fb1', 'pink', '#d63384', '#f4b6c2'), V('Green', '#f0fff0', '#2e9e4f', '#7ed957', '#2e9e4f', '#7ed957')] },
  { b: 'Titan', m: 'Zoop Kids Digital', ref: 'C4040PP01', cat: 'kids', s: 'sportdigital', p: 895, mrp: 995, st: 'rubber', size: '38 mm', wr: '30m', mv: 'Digital Quartz', glass: 'Acrylic', pop: 7, small: true,
    blurb: 'A cool digital watch for kids with alarm and backlight - built for play.',
    feats: ['Alarm', 'Backlight', 'Stopwatch', 'Lightweight'],
    v: [V('Blue', 'black', '#2a6fdb', '#2a6fdb', '#f5c518', '#2a6fdb'), V('Red', 'black', '#e03131', '#e03131', '#ffffff', '#e03131'), V('Purple', 'black', '#7d6bd6', '#7d6bd6', '#ffffff', '#7d6bd6')] },

  // ---------------- FASTRACK ----------------
  { b: 'Fastrack', m: 'Bare Basics Analog', ref: '3120SL01', cat: 'men', s: 'dress', p: 1395, mrp: 1495, st: 'leather', size: '42 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 9,
    blurb: 'Fastrack Bare Basics - youthful, minimal and super affordable. The go-to college watch.',
    feats: ['Leather strap', 'Minimal dial', 'Lightweight'], ind: 'stick',
    v: [V('Black', 'black', 'steel', 'black', '#e03131'), V('Blue', 'blue', 'steel', 'brown', '#ffffff'), V('White', 'white', 'steel', 'tan', '#1d1d1f', '#a8703d')] },
  { b: 'Fastrack', m: 'Stunners Multifunction', ref: '3288KM01', cat: 'men', s: 'chrono', p: 3495, mrp: 3795, st: 'metal', size: '44 mm', wr: '50m', mv: 'Quartz Multifunction', glass: 'Mineral Glass', pop: 8,
    blurb: 'Bold looks and busy dials - Fastrack Stunners is built to turn heads.',
    feats: ['Multifunction sub-dials', 'Stainless steel strap', 'Bold 44mm case'], ind: 'arabic',
    v: [V('All Black', 'black', '#2b2b2b', '#2b2b2b', '#ff6b1a', '#2b2b2b'), V('Blue Steel', 'blue', 'steel', 'steel', '#ffffff'), V('Green', 'green', 'gun', 'gun', '#b5e61d', '#1f4d3a')] },
  { b: 'Fastrack', m: 'Tees Unisex', ref: '38024PP25', cat: 'men', s: 'dress', p: 1195, mrp: 1295, st: 'rubber', size: '40 mm', wr: '30m', mv: 'Quartz', glass: 'Acrylic', pop: 7,
    blurb: 'Colourful, fun and casual - Fastrack Tees matches your mood and your outfit.',
    feats: ['Soft silicone strap', 'Bright colours', 'Lightweight'], ind: 'arabic',
    v: [V('Black', 'black', 'resin', 'black', '#f5c518'), V('Red', 'white', '#e03131', '#e03131', '#e03131', '#e03131'), V('Teal', 'white', '#0f6e6e', '#0f6e6e', '#0f6e6e', '#0f6e6e'), V('Yellow', 'black', '#f5c518', '#f5c518', '#f5c518', '#f5c518')] },
  { b: 'Fastrack', m: 'Vyb Women', ref: 'FV60010SM01', cat: 'women', s: 'dress', p: 2195, mrp: 2395, st: 'mesh', size: '32 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 7, small: true,
    blurb: 'Fastrack Vyb - trendy, minimal and made for the girl on the go.',
    feats: ['Mesh bracelet', 'Minimal dial', 'Slim profile'], ind: 'stick',
    v: [V('Rose Gold', 'pink', 'rose', 'rose', '#8a3b52', '#d9937f'), V('Silver', 'white', 'steel', 'steel', '#1d1d1f', '#dcdde0'), V('Gold', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37')] },
  { b: 'Fastrack', m: 'Limitless FS1 Smartwatch', ref: '38087PP01', cat: 'smart', s: 'smartsq', p: 1995, mrp: 4995, st: 'rubber', size: '1.95" display', wr: 'IP68', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 9,
    blurb: 'Big 1.95" display, Bluetooth calling and a built-in AI voice assistant - smart features at a budget price.',
    feats: ['Bluetooth calling', 'AI voice assistant', '100+ sports modes', 'SpO2 & heart-rate', 'Up to 5 days battery'],
    v: [V('Black', 'black', 'gun', 'black', '#2a6fdb'), V('Blue', 'black', 'steel', 'navy', '#8ccdf5', '#15213b'), V('Olive', 'black', 'gun', 'olive', '#b5e61d', '#4b5a2e'), V('Pink', 'black', 'rose', 'pink', '#ff7f6a', '#f4b6c2')] },
  { b: 'Fastrack', m: 'Reflex Play+ AMOLED', ref: '38054PP01', cat: 'smart', s: 'smartrd', p: 2995, mrp: 5995, st: 'rubber', size: '1.3" AMOLED', wr: 'IP68', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 7,
    blurb: 'A round AMOLED smartwatch with a stylish look - fitness tracking, notifications and more.',
    feats: ['1.3" round AMOLED', 'Heart-rate & SpO2', 'Sleep tracking', 'Up to 7 days battery'],
    v: [V('Black', 'black', 'gun', 'black', '#ff6b1a'), V('Blue', 'black', 'steel', 'navy', '#8ccdf5', '#15213b'), V('Beige', 'black', 'rose', 'beige', '#ff7f6a', '#d9c7a3')] },
  { b: 'Fastrack', m: 'Reflex Beat+ Band', ref: 'SWD90067PP01', cat: 'smart', s: 'band', p: 1299, mrp: 2495, st: 'rubber', size: '1.1" display', wr: 'IP68', mv: 'Fitness Band', glass: 'Tempered Glass', pop: 6,
    blurb: 'A slim, light fitness band that tracks steps, heart-rate and sleep all day long.',
    feats: ['Step & calorie tracking', 'Heart-rate monitor', 'Sleep tracking', '10-day battery'],
    v: [V('Black', 'black', 'black', 'black', '#2a6fdb'), V('Teal', 'black', 'teal', 'teal', '#a6e8cf', '#0f6e6e'), V('Coral', 'black', 'coral', 'coral', '#ffffff', '#ff7f6a')] },
  { b: 'Fastrack', m: 'Digital Sports', ref: '38047PP02', cat: 'sports', s: 'sportdigital', p: 995, mrp: 1095, st: 'rubber', size: '42 mm', wr: '50m', mv: 'Digital Quartz', glass: 'Acrylic', pop: 6,
    blurb: 'A tough, sporty digital from Fastrack - alarm, stopwatch and backlight for everyday action.',
    feats: ['Alarm', 'Stopwatch', 'Backlight', '50m water resistance'],
    v: [V('Black', 'black', 'resin', 'resin', '#ff6b1a'), V('Army Green', 'black', 'olive', 'olive', '#f5c518', '#4b5a2e')] },

  // ---------------- SONATA & BUDGET ----------------
  { b: 'Sonata', m: 'Poze Analog', ref: '77085PP01', cat: 'men', s: 'dress', p: 1395, mrp: 1495, st: 'leather', size: '41 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 8,
    blurb: 'Sonata Poze - stylish everyday looks from the house of Titan, at a price that makes sense.',
    feats: ['Leather strap', 'Date display', 'Titan-made quality'], ind: 'stick', date: true,
    v: [V('Black', 'black', 'steel', 'black', '#c9ccd1'), V('Blue', 'blue', 'steel', 'brown', '#ffffff'), V('Grey', 'grey', 'gun', 'black', '#ff6b1a')] },
  { b: 'Sonata', m: 'Volt Steel', ref: '77104SM01', cat: 'men', s: 'dress', p: 1195, mrp: 1295, st: 'metal', size: '40 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 8,
    blurb: 'A neat steel-bracelet watch for daily wear - smart, simple and budget-friendly.',
    feats: ['Steel bracelet', 'Clean dial'], ind: 'stick',
    v: [V('Black Dial', 'black', 'steel', 'steel', '#c9ccd1'), V('White Dial', 'white', 'steel', 'steel', '#1d1d1f'), V('Blue Dial', 'blue', 'steel', 'steel', '#ffffff')] },
  { b: 'Sonata', m: 'Classic Analog', ref: '7987YL02', cat: 'men', s: 'dress', p: 795, mrp: 895, st: 'leather', size: '38 mm', wr: 'Splash resistant', mv: 'Quartz', glass: 'Mineral Glass', pop: 8,
    blurb: 'An honest, classic analog watch - perfect for daily use, school, office or as a simple gift.',
    feats: ['Leather strap', 'Easy-read dial'], ind: 'roman',
    v: [V('White / Brown', 'white', 'gold', 'brown', '#3a2a05', '#6b4226'), V('Black / Black', 'black', 'steel', 'black', '#c9ccd1')] },
  { b: 'Sonata', m: 'Pankh Women', ref: '8992SM01', cat: 'women', s: 'dress', p: 1195, mrp: 1295, st: 'metal', size: '26 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 7, small: true,
    blurb: 'Light as a feather - Sonata Pankh is an elegant everyday watch for women.',
    feats: ['Slim bracelet', 'Elegant dial'], ind: 'dots',
    v: [V('Silver', 'white', 'steel', 'steel', '#1d1d1f', '#dcdde0'), V('Gold', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37'), V('Rose Gold', 'pink', 'rose', 'rose', '#6b3a2e', '#d9937f')] },
  { b: 'Sonata', m: 'SF Digital', ref: '77037PP01', cat: 'sports', s: 'sportdigital', p: 595, mrp: 695, st: 'rubber', size: '40 mm', wr: '30m', mv: 'Digital Quartz', glass: 'Acrylic', pop: 7,
    blurb: 'Simple, sporty digital with alarm and light - great value for students.',
    feats: ['Alarm', 'Stopwatch', 'Backlight'],
    v: [V('Black', 'black', 'resin', 'resin', '#e03131'), V('Blue', 'black', 'navy', 'navy', '#f5c518', '#15213b')] },
  { b: 'Sonata', m: 'Kids Digital', ref: '87028PP02', cat: 'kids', s: 'sportdigital', p: 449, mrp: 499, st: 'rubber', size: '36 mm', wr: 'Splash resistant', mv: 'Digital Quartz', glass: 'Acrylic', pop: 6, small: true,
    blurb: 'A colourful, easy digital watch for little wrists.',
    feats: ['Backlight', 'Alarm', 'Soft strap'],
    v: [V('Blue', 'black', '#2a6fdb', '#2a6fdb', '#f5c518', '#2a6fdb'), V('Pink', 'black', '#f48fb1', '#f48fb1', '#ffffff', '#f48fb1')] },
  { b: 'TimeVault', m: 'Essentials LED Band', ref: 'TV-LED01', cat: 'kids', s: 'band', p: 129, mrp: 299, st: 'rubber', size: 'One size', wr: 'Splash resistant', mv: 'LED Digital', glass: 'Acrylic', pop: 7, small: true,
    blurb: 'A fun, glowing LED band watch - press the button to see the time light up. Great return gift!',
    feats: ['Bright LED display', 'Soft silicone band', 'Ultra-light'],
    v: [V('Black', 'black', 'black', 'black', '#e03131'), V('Blue', 'black', '#2a6fdb', '#2a6fdb', '#e03131', '#2a6fdb'), V('Pink', 'black', '#f48fb1', '#f48fb1', '#e03131', '#f48fb1'), V('White', 'black', 'white', 'white', '#e03131')] },
  { b: 'TimeVault', m: 'Essentials Kids Cartoon', ref: 'TV-KID02', cat: 'kids', s: 'kidsana', p: 199, mrp: 399, st: 'rubber', size: '32 mm', wr: 'Splash resistant', mv: 'Quartz', glass: 'Acrylic', pop: 6, small: true,
    blurb: 'A cheerful analog watch with big numbers - makes learning time easy and fun.',
    feats: ['Big numbers', 'Soft strap', 'Lightweight'], ind: 'arabic',
    v: [V('Yellow', '#fffbe6', '#f5c518', '#f5c518', '#e03131', '#f5c518'), V('Blue', '#e6f5ff', '#2a6fdb', '#2a6fdb', '#e03131', '#2a6fdb'), V('Purple', '#f5f0ff', '#7d6bd6', '#7d6bd6', '#e03131', '#7d6bd6')] },
  { b: 'TimeVault', m: 'Essentials Classic Analog', ref: 'TV-ESS03', cat: 'men', s: 'dress', p: 349, mrp: 699, st: 'leather', size: '40 mm', wr: 'Splash resistant', mv: 'Quartz', glass: 'Acrylic', pop: 6,
    blurb: 'A neat, classic analog watch at a pocket-friendly price. Great for gifting in bulk.',
    feats: ['Faux-leather strap', 'Easy-read dial'], ind: 'stick',
    v: [V('Black', 'black', 'steel', 'black', '#c9ccd1'), V('White / Brown', 'white', 'gold', 'brown', '#3a2a05', '#6b4226')] },
  { b: 'TimeVault', m: 'Essentials Sports Digital', ref: 'TV-DIG04', cat: 'sports', s: 'sportdigital', p: 299, mrp: 599, st: 'rubber', size: '42 mm', wr: 'Splash resistant', mv: 'Digital Quartz', glass: 'Acrylic', pop: 6,
    blurb: 'A sporty digital watch with alarm and backlight - big value, small price.',
    feats: ['Alarm', 'Stopwatch', 'Backlight'],
    v: [V('Black', 'black', 'resin', 'resin', '#e03131'), V('Army Green', 'black', 'olive', 'olive', '#f5c518', '#4b5a2e'), V('Blue', 'black', 'navy', 'navy', '#8ccdf5', '#15213b')] },

  // ---------------- TIMEX ----------------
  { b: 'Timex', m: 'Weekender 38mm', ref: 'T2N651', cat: 'men', s: 'field', p: 4495, mrp: 4995, st: 'nato', size: '38 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 9,
    blurb: 'The Timex Weekender - a casual classic with a clean military-style dial, Indiglo light and quick-swap straps.',
    feats: ['Indiglo night-light', '24-hour inner track', 'Slip-through fabric strap'], ind: 'field',
    v: [V('Black / Olive', 'black', 'steel', 'olive', '#ffffff', '#4b5a2e'), V('Cream / Navy', 'cream', 'steel', 'navy', '#1d1d1f', '#15213b'), V('Blue / Tan', 'navy', 'steel', 'tan', '#ffffff', '#a8703d')] },
  { b: 'Timex', m: 'Expedition Scout 40', ref: 'TW4B09200', cat: 'men', s: 'field', p: 5495, mrp: 5995, st: 'leather', size: '40 mm', wr: '50m', mv: 'Quartz', glass: 'Mineral Glass', pop: 8,
    blurb: 'Built for the outdoors - Expedition Scout is rugged, readable and ready for adventure.',
    feats: ['Indiglo night-light', 'Date window', 'Leather strap', '50m water resistance'], ind: 'field', date: true,
    v: [V('Black / Brown', 'black', 'steel', 'brown', '#ffffff', '#6b4226'), V('Green / Tan', 'dgreen', 'steel', 'tan', '#ffffff', '#a8703d'), V('Cream / Black', 'cream', 'steel', 'black', '#1d1d1f')] },
  { b: 'Timex', m: 'Easy Reader', ref: 'TW2R62300', cat: 'men', s: 'dress', p: 3995, mrp: 4295, st: 'leather', size: '38 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 7,
    blurb: 'Since 1977, the Easy Reader has been the simple, honest watch - big numbers, clear dial, Indiglo light.',
    feats: ['Big, clear numbers', 'Indiglo night-light', 'Leather strap'], ind: 'arabic',
    v: [V('White / Brown', 'white', 'gold', 'brown', '#1d1d1f', '#6b4226'), V('White / Black', 'white', 'steel', 'black', '#1d1d1f', '#151515')] },
  { b: 'Timex', m: 'Fria Women', ref: 'TWEL14801', cat: 'women', s: 'dress', p: 4995, mrp: 5495, st: 'mesh', size: '30 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 6, small: true,
    blurb: 'Soft, modern and feminine - the Timex Fria has a slim case and a smooth mesh bracelet.',
    feats: ['Mesh bracelet', 'Slim case', 'Minimal dial'], ind: 'stick',
    v: [V('Rose Gold', 'pink', 'rose', 'rose', '#6b3a2e', '#d9937f'), V('Silver', 'white', 'steel', 'steel', '#1d1d1f', '#dcdde0')] },
  { b: 'Timex', m: 'Q Timex Reissue', ref: 'TW2T80700', cat: 'premium', s: 'diver', p: 14995, mrp: 15995, st: 'metal', size: '38 mm', wr: '50m', mv: 'Quartz', glass: 'Acrylic Dome', pop: 7,
    blurb: 'A faithful reissue of the 1979 Q Timex - the famous "Pepsi" bezel, woven bracelet and pure retro cool.',
    feats: ['Iconic two-tone bezel', 'Day & date', 'Woven steel bracelet', 'Battery hatch on the back'], ind: 'stick', date: true, bezel2: true,
    v: [V('Pepsi Blue/Red', 'navy', 'steel', 'steel', '#a3161f', '#a3161f'), V('Black', 'black', 'steel', 'steel', '#151515', '#151515')] },
  { b: 'Timex', m: 'Marlin Automatic', ref: 'TW2T22700', cat: 'premium', s: 'dress', p: 19995, mrp: 21995, st: 'leather', size: '40 mm', wr: '30m', mv: 'Automatic (Self-winding)', glass: 'Acrylic Dome', pop: 5,
    blurb: 'A 1960s design classic reborn with an automatic movement - vintage elegance for the true watch lover.',
    feats: ['Automatic movement', 'Exhibition case back', 'Domed crystal', 'Leather strap'], ind: 'arabic', auto: true,
    v: [V('Silver / Brown', 'silver', 'steel', 'brown', '#1d1d1f', '#6b4226'), V('Black / Black', 'black', 'steel', 'black', '#c9ccd1')] },

  // ---------------- FOSSIL & FASHION ----------------
  { b: 'Fossil', m: 'Grant Chronograph', ref: 'FS4735', cat: 'chrono', s: 'chrono', p: 12995, mrp: 13995, st: 'leather', size: '44 mm', wr: '50m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 9,
    blurb: 'The Fossil Grant - roman numerals, a chronograph dial and rich leather. One of Fossil\'s best-selling watches of all time.',
    feats: ['Chronograph', 'Roman numeral dial', 'Genuine leather strap', 'Date window'], ind: 'roman',
    v: [V('White / Brown', 'white', 'steel', 'brown', '#1d1d1f', '#6b4226'), V('Black / Black', 'black', 'steel', 'black', '#c9ccd1'), V('Blue / Brown', 'navy', 'rose', 'brown', '#ffffff', '#15213b')] },
  { b: 'Fossil', m: 'Neutra Chronograph', ref: 'FS5381', cat: 'chrono', s: 'chrono', p: 13995, mrp: 14995, st: 'leather', size: '44 mm', wr: '50m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 7,
    blurb: 'Clean, modern and minimal - the Neutra chronograph is refined everyday luxury.',
    feats: ['Chronograph', 'Date window', 'Genuine leather strap'], ind: 'stick', date: true,
    v: [V('Navy / Brown', 'navy', 'steel', 'brown', '#ffffff', '#15213b'), V('Black / Black', 'black', 'gun', 'black', '#c9ccd1'), V('Green / Tan', 'dgreen', 'gold', 'tan', '#ffffff', '#123a2c')] },
  { b: 'Fossil', m: 'Machine Chronograph', ref: 'FS4552', cat: 'chrono', s: 'chrono', p: 12995, mrp: 13995, st: 'metal', size: '45 mm', wr: '50m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 8,
    blurb: 'Industrial, bold and built to impress - the all-black Fossil Machine is a modern classic.',
    feats: ['Chronograph', 'Tachymeter bezel', 'Date window', 'Stainless steel bracelet'], ind: 'arabic', tachy: true, date: true,
    v: [V('All Black', 'black', '#2b2b2b', '#2b2b2b', '#c9ccd1', '#2b2b2b'), V('Gunmetal', 'black', 'gun', 'gun', '#ff6b1a', '#4a4d52'), V('Steel', 'black', 'steel', 'steel', '#e03131', '#c9ccd1')] },
  { b: 'Fossil', m: 'Townsman Automatic', ref: 'ME3110', cat: 'premium', s: 'dress', p: 19995, mrp: 21995, st: 'leather', size: '44 mm', wr: '50m', mv: 'Automatic (Self-winding)', glass: 'Mineral Glass', pop: 6,
    blurb: 'A beautiful open-heart automatic - see the movement beating through the dial.',
    feats: ['Automatic movement', 'Open-heart dial', 'Exhibition case back', 'Genuine leather'], ind: 'roman', auto: true, openheart: true,
    v: [V('Black / Brown', 'black', 'steel', 'brown', '#d4af37', '#6b4226'), V('Silver / Black', 'silver', 'steel', 'black', '#1d1d1f', '#dcdde0'), V('Blue / Brown', 'navy', 'rose', 'brown', '#d9937f', '#15213b')] },
  { b: 'Fossil', m: 'Minimalist Slim', ref: 'FS5447', cat: 'men', s: 'dress', p: 9995, mrp: 10995, st: 'leather', size: '44 mm', wr: '50m', mv: 'Quartz', glass: 'Mineral Glass', pop: 7,
    blurb: 'Less is more - a slim, minimal three-hand watch that goes with everything.',
    feats: ['Slim case', 'Minimal dial', 'Genuine leather strap'], ind: 'stick',
    v: [V('Black / Black', 'black', 'gun', 'black', '#c9ccd1'), V('White / Brown', 'white', 'steel', 'brown', '#1d1d1f', '#6b4226'), V('Navy / Tan', 'navy', 'rose', 'tan', '#ffffff', '#15213b')] },
  { b: 'Fossil', m: 'Jacqueline Women', ref: 'ES3546', cat: 'women', s: 'dress', p: 9495, mrp: 9995, st: 'leather', size: '36 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 8, small: true,
    blurb: 'Fossil Jacqueline - soft, feminine and endlessly elegant with a date window and leather strap.',
    feats: ['Date window', 'Genuine leather strap', 'Roman numerals'], ind: 'roman', date: true,
    v: [V('Blush / Rose Gold', 'ivory', 'rose', 'pink', '#6b3a2e', '#f4b6c2'), V('White / Brown', 'white', 'rose', 'brown', '#6b3a2e', '#6b4226'), V('Black', 'black', 'steel', 'black', '#c9ccd1')] },
  { b: 'Fossil', m: 'Carlie Women', ref: 'ES4341', cat: 'women', s: 'dress', p: 10495, mrp: 10995, st: 'mesh', size: '28 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 7, small: true,
    blurb: 'Petite, glamorous and oh-so-pretty - Fossil Carlie with a mesh bracelet is a gift she\'ll love.',
    feats: ['Petite 28mm case', 'Mesh bracelet', 'Crystal accents'], ind: 'dots',
    v: [V('Rose Gold', 'pink', 'rose', 'rose', '#6b3a2e', '#d9937f'), V('Gold', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37'), V('Silver', 'white', 'steel', 'steel', '#1d1d1f', '#dcdde0')] },
  { b: 'Daniel Wellington', m: 'Classic Petite 32', ref: 'DW00100163', cat: 'women', s: 'dress', p: 13999, mrp: 14999, st: 'mesh', size: '32 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 8, small: true,
    blurb: 'The Scandinavian minimal classic - an ultra-clean dial and a sleek mesh strap. A true wardrobe essential.',
    feats: ['Ultra-slim 6mm case', 'Mesh strap', 'Minimal dial'], ind: 'none',
    v: [V('Rose Gold / White', 'white', 'rose', 'rose', '#6b3a2e', '#d9937f'), V('Silver / Black', 'black', 'steel', 'steel', '#dcdde0', '#151515'), V('Gold / White', 'white', 'gold', 'gold', '#3a2a05', '#d4af37')] },
  { b: 'Tommy Hilfiger', m: 'Decker Multifunction', ref: 'TH1791349', cat: 'premium', s: 'chrono', p: 14999, mrp: 15999, st: 'leather', size: '44 mm', wr: '50m', mv: 'Quartz Multifunction', glass: 'Mineral Glass', pop: 7,
    blurb: 'Classic American style - the Decker brings sporty sub-dials and signature Tommy colours.',
    feats: ['Day, date & 24-hour sub-dials', 'Genuine leather strap', 'Signature red-white-blue accents'], ind: 'arabic',
    v: [V('Navy / Brown', 'navy', 'steel', 'brown', '#e03131', '#15213b'), V('Black / Black', 'black', 'steel', 'black', '#e03131')] },
  { b: 'Armani Exchange', m: 'Hampton Chronograph', ref: 'AX2104', cat: 'premium', s: 'chrono', p: 14995, mrp: 16495, st: 'metal', size: '46 mm', wr: '50m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 7,
    blurb: 'Big, bold and all-black - the Armani Exchange Hampton is a fashion icon for men.',
    feats: ['Chronograph', 'Date window', 'Stainless steel bracelet'], ind: 'stick', date: true,
    v: [V('All Black', 'black', '#2b2b2b', '#2b2b2b', '#c9ccd1', '#2b2b2b'), V('Steel / Blue', 'blue', 'steel', 'steel', '#ffffff', '#1d4f8c'), V('Gold / Black', 'black', 'gold', 'gold', '#d4af37', '#d4af37')] },
  { b: 'Michael Kors', m: 'Pyper Women', ref: 'MK2750', cat: 'premium', s: 'dress', p: 16995, mrp: 17995, st: 'metal', size: '38 mm', wr: '50m', mv: 'Quartz', glass: 'Mineral Glass', pop: 6, small: true,
    blurb: 'Luxe and polished - the Michael Kors Pyper is a signature piece for every occasion.',
    feats: ['Stainless steel bracelet', 'Signature logo dial', 'Polished finish'], ind: 'stick',
    v: [V('Gold', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37'), V('Rose Gold', 'pink', 'rose', 'rose', '#6b3a2e', '#d9937f'), V('Silver', 'white', 'steel', 'steel', '#1d1d1f', '#dcdde0')] },
  { b: 'Skagen', m: 'Signatur Slim', ref: 'SKW6356', cat: 'premium', s: 'dress', p: 11995, mrp: 12995, st: 'mesh', size: '40 mm', wr: '50m', mv: 'Quartz', glass: 'Mineral Glass', pop: 5,
    blurb: 'Danish design at its finest - ultra-slim and quietly beautiful on a fine mesh bracelet.',
    feats: ['Ultra-slim case', 'Mesh bracelet', 'Minimal Danish design'], ind: 'stick',
    v: [V('Silver / Blue', 'navy', 'steel', 'steel', '#ffffff', '#15213b'), V('Black', 'black', '#2b2b2b', '#2b2b2b', '#c9ccd1', '#2b2b2b')] },
  { b: 'Maserati', m: 'Successo Chronograph', ref: 'R8873621009', cat: 'premium', s: 'chrono', p: 16999, mrp: 18999, st: 'metal', size: '44 mm', wr: '100m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 5,
    blurb: 'Italian racing heritage on your wrist - a sporty, luxurious chronograph with a sharp tachymeter bezel.',
    feats: ['Chronograph', 'Tachymeter bezel', 'Date window', '100m water resistance'], ind: 'stick', tachy: true, date: true,
    v: [V('Blue', 'blue', 'steel', 'steel', '#ffffff'), V('Black Gold', 'black', 'gold', 'gold', '#d4af37', '#151515')] },

  // ---------------- SEIKO / CITIZEN / HMT ----------------
  { b: 'Seiko', m: '5 Automatic SNK809', ref: 'SNK809K2', cat: 'premium', s: 'field', p: 12500, mrp: 13500, st: 'nato', size: '37 mm', wr: '30m', mv: 'Automatic (Self-winding)', glass: 'Hardlex Crystal', pop: 8,
    blurb: 'The legendary "baby field watch" - a Japanese automatic that watch lovers call the best value in the world.',
    feats: ['Automatic 7S26 movement', 'Day & date', 'Exhibition case back', 'Luminous hands & markers'], ind: 'field', date: true, auto: true,
    v: [V('Black / Black', 'black', 'steel', 'black', '#ffffff'), V('Blue / Blue', 'navy', 'steel', 'navy', '#ffffff'), V('Green / Green', 'dgreen', 'steel', 'olive', '#ffffff', '#123a2c')] },
  { b: 'Seiko', m: 'Classic SUR Quartz', ref: 'SUR309P1', cat: 'premium', s: 'dress', p: 15500, mrp: 16500, st: 'metal', size: '40 mm', wr: '100m', mv: 'Quartz', glass: 'Hardlex Crystal', pop: 6,
    blurb: 'Seiko precision and timeless design - a refined steel dress watch built to last a lifetime.',
    feats: ['Seiko quartz precision', 'Date window', '100m water resistance', 'Stainless steel bracelet'], ind: 'stick', date: true,
    v: [V('Blue Dial', 'blue', 'steel', 'steel', '#ffffff'), V('White Dial', 'white', 'steel', 'steel', '#1d1d1f'), V('Green Dial', 'green', 'steel', 'steel', '#ffffff')] },
  { b: 'Citizen', m: 'Eco-Drive Field', ref: 'BM8180-03E', cat: 'premium', s: 'field', p: 14500, mrp: 15500, st: 'fabric', size: '42 mm', wr: '100m', mv: 'Eco-Drive (Solar)', glass: 'Mineral Glass', pop: 7,
    blurb: 'Powered by any light, never needs a battery - the Citizen Eco-Drive field watch is built for life.',
    feats: ['Eco-Drive solar power', 'No battery change needed', '100m water resistance', '24-hour inner track', 'Date window'], ind: 'field', date: true,
    v: [V('Black / Black', 'black', 'steel', 'black', '#ffffff'), V('Khaki / Olive', 'olive', 'steel', 'olive', '#ffffff', '#4b5a2e')] },
  { b: 'Citizen', m: 'Quartz Dress BI5000', ref: 'BI5000-87E', cat: 'men', s: 'dress', p: 6495, mrp: 6995, st: 'metal', size: '40 mm', wr: '50m', mv: 'Quartz', glass: 'Mineral Glass', pop: 7,
    blurb: 'Japanese quality at an honest price - a crisp steel watch with date, perfect for work.',
    feats: ['Date window', 'Stainless steel', 'Luminous hands'], ind: 'stick', date: true,
    v: [V('Black Dial', 'black', 'steel', 'steel', '#c9ccd1'), V('White Dial', 'white', 'steel', 'steel', '#1d1d1f'), V('Blue Dial', 'blue', 'steel', 'steel', '#ffffff')] },
  { b: 'HMT', m: 'Janata Hand-wound', ref: 'JNSL-02', cat: 'men', s: 'dress', p: 2495, mrp: 2695, st: 'leather', size: '35 mm', wr: 'Splash resistant', mv: 'Mechanical Hand-wound', glass: 'Acrylic', pop: 8,
    blurb: "A piece of India's history - the iconic HMT Janata, a hand-wound mechanical watch with no battery needed.",
    feats: ['Mechanical hand-wound (no battery)', '17 jewels', 'Classic Indian heritage'], ind: 'arabic', auto: true,
    v: [V('White / Black', 'white', 'steel', 'black', '#1d1d1f'), V('Black / Brown', 'black', 'steel', 'brown', '#ffffff', '#6b4226'), V('Cream / Tan', 'cream', 'gold', 'tan', '#3a2a05', '#a8703d')] },
  { b: 'HMT', m: 'Pilot Classic', ref: 'PLT-01', cat: 'men', s: 'field', p: 2995, mrp: 3195, st: 'leather', size: '37 mm', wr: 'Splash resistant', mv: 'Mechanical Hand-wound', glass: 'Acrylic', pop: 6,
    blurb: 'The HMT Pilot - a collector-favourite mechanical watch with a bold, readable aviation dial.',
    feats: ['Mechanical hand-wound', 'Luminous numerals', 'Collector favourite'], ind: 'field',
    v: [V('Black / Brown', 'black', 'steel', 'brown', '#ffffff', '#6b4226'), V('Blue / Black', 'navy', 'steel', 'black', '#ffffff', '#15213b')] },

  // ---------------- SMARTWATCHES ----------------
  { b: 'Noise', m: 'ColorFit Pro 5', ref: 'NOI-CFP5', cat: 'smart', s: 'smartsq', p: 3999, mrp: 7999, st: 'rubber', size: '1.85" AMOLED', wr: 'IP68', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 10,
    blurb: 'Noise ColorFit Pro 5 - a big 1.85" AMOLED, Bluetooth calling and smart health tracking in a premium metal body.',
    feats: ['1.85" AMOLED display', 'Bluetooth calling', 'Heart-rate, SpO2 & stress', '100+ sports modes', 'Up to 7 days battery'],
    v: [V('Jet Black', 'black', 'gun', 'black', '#2a6fdb'), V('Midnight Blue', 'black', 'steel', 'navy', '#8ccdf5', '#15213b'), V('Rose Pink', 'black', 'rose', 'pink', '#ff7f6a', '#f4b6c2'), V('Olive Green', 'black', 'gun', 'olive', '#b5e61d', '#4b5a2e')] },
  { b: 'Noise', m: 'ColorFit Icon 2', ref: 'NOI-CFI2', cat: 'smart', s: 'smartsq', p: 1299, mrp: 5999, st: 'rubber', size: '1.8" display', wr: 'IP67', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 10,
    blurb: "One of India's best-selling smartwatches - big display, Bluetooth calling and AI voice assistant at an amazing price.",
    feats: ['1.8" display', 'Bluetooth calling', 'AI voice assistant', 'Heart-rate & SpO2', '60 sports modes'],
    v: [V('Jet Black', 'black', 'gun', 'black', '#2a6fdb'), V('Vintage Brown', 'black', 'gold', 'brown', '#f5c518', '#6b4226'), V('Mist Grey', 'black', 'steel', 'grey', '#8ccdf5', '#5a5d63'), V('Rose Pink', 'black', 'rose', 'pink', '#ff7f6a', '#f4b6c2')] },
  { b: 'Noise', m: 'NoiseFit Halo 2', ref: 'NOI-HALO2', cat: 'smart', s: 'smartrd', p: 3499, mrp: 7999, st: 'metal', size: '1.43" AMOLED', wr: 'IP68', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 7,
    blurb: 'A classy round smartwatch with a metal body and AMOLED display - looks like a luxury watch, works like a smartwatch.',
    feats: ['1.43" round AMOLED', 'Always-on display', 'Bluetooth calling', 'Metal strap', 'Up to 7 days battery'],
    v: [V('Elite Silver', 'black', 'steel', 'steel', '#8ccdf5', '#c9ccd1'), V('Elite Black', 'black', '#2b2b2b', '#2b2b2b', '#ff6b1a', '#2b2b2b'), V('Rose Gold', 'black', 'rose', 'rose', '#ff7f6a', '#d9937f')] },
  { b: 'Noise', m: 'Twist Round', ref: 'NOI-TWIST', cat: 'smart', s: 'smartrd', p: 1499, mrp: 5999, st: 'rubber', size: '1.38" display', wr: 'IP68', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 8,
    blurb: 'Round, stylish and super affordable - Noise Twist gives you Bluetooth calling and health tracking in a classic shape.',
    feats: ['1.38" round display', 'Bluetooth calling', 'Heart-rate & SpO2', 'Up to 7 days battery'],
    v: [V('Jet Black', 'black', 'gun', 'black', '#2a6fdb'), V('Silver Grey', 'black', 'steel', 'grey', '#8ccdf5', '#5a5d63'), V('Rose Pink', 'black', 'rose', 'pink', '#ff7f6a', '#f4b6c2')] },
  { b: 'boAt', m: 'Wave Call 2', ref: 'BOAT-WC2', cat: 'smart', s: 'smartsq', p: 1299, mrp: 6999, st: 'rubber', size: '1.83" display', wr: 'IP68', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 10,
    blurb: 'boAt Wave Call 2 - Bluetooth calling, 700+ active modes and a big HD display. A massive best-seller.',
    feats: ['1.83" HD display', 'Bluetooth calling', '700+ active modes', 'Heart-rate & SpO2', 'Up to 7 days battery'],
    v: [V('Active Black', 'black', 'gun', 'black', '#ff3b3b'), V('Deep Blue', 'black', 'steel', 'navy', '#8ccdf5', '#15213b'), V('Cherry Blossom', 'black', 'rose', 'pink', '#ff7f6a', '#f4b6c2'), V('Olive Green', 'black', 'gun', 'olive', '#b5e61d', '#4b5a2e')] },
  { b: 'boAt', m: 'Storm Call 3', ref: 'BOAT-SC3', cat: 'smart', s: 'smartsq', p: 1499, mrp: 7499, st: 'rubber', size: '1.83" display', wr: 'IP67', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 8,
    blurb: 'Smart turn-by-turn navigation, Bluetooth calling and a sleek design - the boAt Storm Call 3 does it all.',
    feats: ['Turn-by-turn navigation (MapMyIndia)', 'Bluetooth calling', 'QR code payments tray', 'Heart-rate & SpO2'],
    v: [V('Active Black', 'black', 'gun', 'black', '#ff3b3b'), V('Cherry Blossom', 'black', 'rose', 'pink', '#ff7f6a', '#f4b6c2'), V('Teal Green', 'black', 'steel', 'teal', '#a6e8cf', '#0f6e6e')] },
  { b: 'boAt', m: 'Lunar Discovery', ref: 'BOAT-LD', cat: 'smart', s: 'smartrd', p: 2299, mrp: 7999, st: 'rubber', size: '1.39" display', wr: 'IP68', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 7,
    blurb: 'A premium round smartwatch with a metal body, Bluetooth calling and a functional crown.',
    feats: ['1.39" round HD display', 'Functional crown', 'Bluetooth calling', 'Metallic build'],
    v: [V('Active Black', 'black', 'gun', 'black', '#ff3b3b'), V('Steel Blue', 'black', 'steel', 'navy', '#8ccdf5', '#15213b'), V('Metal Silver', 'black', 'steel', 'steel', '#8ccdf5', '#c9ccd1')] },
  { b: 'Fire-Boltt', m: 'Ninja Call Pro Plus', ref: 'FB-NCPP', cat: 'smart', s: 'smartsq', p: 1099, mrp: 8999, st: 'rubber', size: '1.83" display', wr: 'IP67', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 10,
    blurb: 'Fire-Boltt Ninja Call Pro Plus - Bluetooth calling, AI voice assistant and 100 sports modes at an unbeatable price.',
    feats: ['1.83" HD display', 'Bluetooth calling', 'AI voice assistant', '100 sports modes', 'Heart-rate & SpO2'],
    v: [V('Black', 'black', 'gun', 'black', '#ff6b1a'), V('Grey', 'black', 'steel', 'grey', '#8ccdf5', '#5a5d63'), V('Pink', 'black', 'rose', 'pink', '#ff7f6a', '#f4b6c2'), V('Navy', 'black', 'steel', 'navy', '#8ccdf5', '#15213b')] },
  { b: 'Fire-Boltt', m: 'Phoenix Pro', ref: 'FB-PHXP', cat: 'smart', s: 'smartrd', p: 1599, mrp: 9999, st: 'metal', size: '1.39" display', wr: 'IP67', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 8,
    blurb: 'A luxury-look round smartwatch with a metal strap, Bluetooth calling and 120+ sports modes.',
    feats: ['1.39" round display', 'Metal strap', 'Bluetooth calling', '120+ sports modes'],
    v: [V('Silver', 'black', 'steel', 'steel', '#8ccdf5', '#c9ccd1'), V('Black', 'black', '#2b2b2b', '#2b2b2b', '#ff6b1a', '#2b2b2b'), V('Gold', 'black', 'gold', 'gold', '#f5c518', '#d4af37')] },
  { b: 'Fire-Boltt', m: 'Visionary AMOLED', ref: 'FB-VIS', cat: 'smart', s: 'smartsq', p: 2999, mrp: 12999, st: 'rubber', size: '1.78" AMOLED', wr: 'IP68', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 7,
    blurb: 'A gorgeous 1.78" AMOLED display with a rotating crown and always-on mode.',
    feats: ['1.78" AMOLED display', 'Rotating crown', 'Always-on display', 'Bluetooth calling'],
    v: [V('Black', 'black', 'gun', 'black', '#ff6b1a'), V('Gold Pink', 'black', 'gold', 'pink', '#ff7f6a', '#f4b6c2'), V('Silver Blue', 'black', 'steel', 'navy', '#8ccdf5', '#15213b')] },
  { b: 'Amazfit', m: 'Bip 5', ref: 'A2215', cat: 'smart', s: 'smartsq', p: 6999, mrp: 8999, st: 'rubber', size: '1.91" display', wr: 'IP68', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 8,
    blurb: 'Huge 1.91" display, built-in GPS and up to 10 days of battery - Amazfit Bip 5 is a fitness powerhouse.',
    feats: ['Built-in GPS', '1.91" display', 'Up to 10 days battery', 'Bluetooth calling', 'Alexa built-in'],
    v: [V('Soft Black', 'black', 'gun', 'black', '#ff6b1a'), V('Cream White', 'black', 'white', 'cream', '#ff6b1a', '#f1e8d2'), V('Pastel Pink', 'black', 'pink', 'pink', '#ff7f6a', '#f4b6c2')] },
  { b: 'Amazfit', m: 'Active', ref: 'A2211', cat: 'smart', s: 'smartsq', p: 11999, mrp: 14999, st: 'rubber', size: '1.75" AMOLED', wr: '5 ATM', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 6,
    blurb: 'Light, stylish and smart - built-in GPS, AI fitness coach and up to 14 days of battery.',
    feats: ['1.75" AMOLED display', 'Built-in GPS', 'AI fitness coach (Zepp Coach)', 'Up to 14 days battery', '5 ATM water resistance'],
    v: [V('Midnight Black', 'black', 'gun', 'black', '#2a6fdb'), V('Petal Pink', 'black', 'rose', 'pink', '#ff7f6a', '#f4b6c2'), V('Lavender Purple', 'black', 'steel', 'lavender', '#7d6bd6', '#c8b8f0')] },
  { b: 'Amazfit', m: 'GTR 4', ref: 'A2166', cat: 'smart', s: 'smartrd', p: 13999, mrp: 16999, st: 'leather', size: '1.43" AMOLED', wr: '5 ATM', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 6,
    blurb: 'A classic round smartwatch with dual-band GPS, Alexa and up to 14 days of battery - premium in every way.',
    feats: ['Dual-band GPS', '1.43" AMOLED', 'Alexa built-in', 'Up to 14 days battery', 'Bluetooth calling'],
    v: [V('Superspeed Black', 'black', '#2b2b2b', 'black', '#ff6b1a', '#2b2b2b'), V('Vintage Brown', 'black', 'steel', 'brown', '#f5c518', '#6b4226'), V('Racetrack Grey', 'black', 'steel', 'grey', '#8ccdf5', '#5a5d63')] },
  { b: 'Samsung', m: 'Galaxy Watch FE', ref: 'SM-R861', cat: 'smart', s: 'smartrd', p: 14999, mrp: 19999, st: 'rubber', size: '40 mm', wr: '5 ATM + IP68', mv: 'Smartwatch (Wear OS)', glass: 'Sapphire Crystal', pop: 7,
    blurb: 'The Galaxy Watch experience at a great price - advanced health tracking, Google apps and a sapphire crystal display.',
    feats: ['Wear OS with Google apps', 'BioActive health sensor', 'Sapphire crystal', 'Sleep coaching', 'Samsung Wallet'],
    v: [V('Black', 'black', '#2b2b2b', 'black', '#2a6fdb', '#2b2b2b'), V('Silver', 'black', 'steel', 'steel', '#8ccdf5', '#c9ccd1'), V('Pink Gold', 'black', 'rose', 'pink', '#ff7f6a', '#f4b6c2')] },
  { b: 'Samsung', m: 'Galaxy Fit3', ref: 'SM-R390', cat: 'smart', s: 'band', p: 4999, mrp: 5999, st: 'rubber', size: '1.6" AMOLED', wr: '5 ATM + IP68', mv: 'Fitness Band', glass: 'Tempered Glass', pop: 7,
    blurb: 'A big 1.6" AMOLED fitness band with 100+ workouts and up to 13 days of battery.',
    feats: ['1.6" AMOLED', '100+ workout modes', 'Up to 13 days battery', 'Sleep coaching'],
    v: [V('Dark Grey', 'black', 'gun', 'gun', '#2a6fdb', '#4a4d52'), V('Silver', 'black', 'steel', 'white', '#2a6fdb', '#dcdde0'), V('Pink Gold', 'black', 'rose', 'pink', '#ff7f6a', '#f4b6c2')] },
  { b: 'Xiaomi', m: 'Smart Band 9', ref: 'M2345B1', cat: 'smart', s: 'band', p: 3999, mrp: 4499, st: 'rubber', size: '1.62" AMOLED', wr: '5 ATM', mv: 'Fitness Band', glass: 'Tempered Glass', pop: 8,
    blurb: 'The world\'s favourite fitness band - bright AMOLED, 150+ sports modes and up to 21 days of battery.',
    feats: ['1.62" AMOLED', '150+ sports modes', 'Up to 21 days battery', 'Heart-rate & SpO2'],
    v: [V('Midnight Black', 'black', 'black', 'black', '#ff6b1a'), V('Arctic Blue', 'black', 'sky', 'sky', '#2a6fdb', '#8ccdf5'), V('Mystic Rose', 'black', 'rose', 'pink', '#ff7f6a', '#f4b6c2')] },
  { b: 'Redmi', m: 'Watch 5 Active', ref: 'M2351W1', cat: 'smart', s: 'smartsq', p: 2799, mrp: 4999, st: 'rubber', size: '2" display', wr: '5 ATM', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 8,
    blurb: 'A massive 2" display, Bluetooth calling and up to 18 days of battery at a Redmi price.',
    feats: ['2" LCD display', 'Bluetooth calling', 'Up to 18 days battery', '5 ATM water resistance'],
    v: [V('Matte Black', 'black', 'gun', 'black', '#ff6b1a'), V('Silver Grey', 'black', 'steel', 'grey', '#8ccdf5', '#5a5d63')] },
  { b: 'CMF by Nothing', m: 'Watch Pro 2', ref: 'CMF-WP2', cat: 'smart', s: 'smartrd', p: 4999, mrp: 5999, st: 'rubber', size: '1.32" AMOLED', wr: 'IP68', mv: 'Smartwatch', glass: 'Tempered Glass', pop: 7,
    blurb: 'Bold design with an interchangeable bezel - the CMF Watch Pro 2 stands out from the crowd.',
    feats: ['Interchangeable bezel', '1.32" AMOLED', 'Built-in GPS', 'Bluetooth calling', 'Up to 11 days battery'],
    v: [V('Dark Grey', 'black', 'gun', 'grey', '#ff6b1a', '#5a5d63'), V('Ash Grey', 'black', 'steel', '#9a9ca0', '#ff6b1a', '#9a9ca0'), V('Orange', 'black', 'gun', 'orange', '#ff6b1a', '#ff6b1a')] },
  { b: 'OnePlus', m: 'Watch 2R', ref: 'OPW2R', cat: 'smart', s: 'smartrd', p: 17999, mrp: 17999, st: 'rubber', size: '1.43" AMOLED', wr: '5 ATM + IP68', mv: 'Smartwatch (Wear OS)', glass: 'Tempered Glass', pop: 6,
    blurb: 'Wear OS smartwatch with up to 100 hours of battery, dual-band GPS and a premium aluminium build.',
    feats: ['Wear OS with Google apps', 'Up to 100 hours battery', 'Dual-band GPS', '1.43" AMOLED'],
    v: [V('Gunmetal Grey', 'black', 'gun', 'gun', '#ff3b3b', '#4a4d52'), V('Forest Green', 'black', 'gun', 'dgreen', '#b5e61d', '#123a2c')] },
  // ---------------- MORE BESTSELLERS ----------------
  { b: 'Casio', m: 'Illuminator MRW-200H Diver', ref: 'MRW-200H-1BV', cat: 'men', s: 'diver', p: 1995, mrp: 2195, st: 'resin', size: '44.6 mm', wr: '100m', mv: 'Quartz', glass: 'Mineral Glass', pop: 9,
    blurb: 'The budget diver everyone recommends - rotating bezel, 100m water resistance and a date window for under ₹2,000.',
    feats: ['Rotating bezel', 'Date display', 'Luminous hands', '100m water resistance'], ind: 'arabic', date: true,
    v: [V('Black', 'black', 'resin', 'resin', '#e03131'), V('Navy Blue', 'navy', '#1f2f55', '#1f2f55', '#ffffff', '#15213b'), V('Olive', 'olive', 'olive', 'olive', '#f5c518', '#4b5a2e')] },
  { b: 'Casio', m: 'Youth F-108WH', ref: 'F-108WH-1A', cat: 'kids', s: 'sportdigital', p: 1395, mrp: 1495, st: 'resin', size: '40.8 mm', wr: 'Water Resistant', mv: 'Digital Quartz', glass: 'Resin Glass', pop: 7, small: true,
    blurb: 'A simple, sturdy digital with a bright LED light - perfect for teens and school.',
    feats: ['LED illuminator', 'Alarm', 'Stopwatch', '7-year battery'],
    v: [V('Black', 'black', 'resin', 'resin', '#3a7bd5'), V('Blue', 'black', 'navy', 'navy', '#f5c518', '#15213b')] },
  { b: 'Casio', m: 'Sheen SHE-4540', ref: 'SHE-4540CGM-4A', cat: 'women', s: 'dress', p: 8995, mrp: 9495, st: 'metal', size: '32 mm', wr: '50m', mv: 'Quartz', glass: 'Sapphire Crystal', pop: 6, small: true,
    blurb: 'Casio Sheen - graceful styling with Swarovski crystal accents and a scratch-proof sapphire crystal.',
    feats: ['Sapphire crystal', 'Crystal markers', 'Stainless steel bracelet'], ind: 'dots',
    v: [V('Rose Gold', 'pink', 'rose', 'rose', '#6b3a2e', '#d9937f'), V('Silver', 'white', 'steel', 'steel', '#1d1d1f', '#dcdde0')] },
  { b: 'Sonata', m: 'Wedding Gold Women', ref: '87029YM01', cat: 'women', s: 'dress', p: 1695, mrp: 1895, st: 'jubilee', size: '24 mm', wr: 'Splash resistant', mv: 'Quartz', glass: 'Mineral Glass', pop: 7, small: true,
    blurb: 'A festive, gold-toned bracelet watch - an affordable gift for weddings and celebrations.',
    feats: ['Gold-tone bracelet', 'Stone-studded dial', 'Gift box'], ind: 'dots',
    v: [V('Gold', 'champagne', 'gold', 'gold', '#3a2a05', '#d4af37'), V('Rose Gold', 'pink', 'rose', 'rose', '#6b3a2e', '#d9937f')] },
  { b: 'Timex', m: 'Classic Women Leather', ref: 'TW2R65400', cat: 'women', s: 'dress', p: 2995, mrp: 3295, st: 'leather', size: '30 mm', wr: '30m', mv: 'Quartz', glass: 'Mineral Glass', pop: 6, small: true,
    blurb: 'Timeless and easy to wear - a classic leather watch with a clear, elegant dial.',
    feats: ['Indiglo night-light', 'Leather strap', 'Easy-read dial'], ind: 'arabic',
    v: [V('White / Tan', 'white', 'gold', 'tan', '#3a2a05', '#a8703d'), V('White / Black', 'white', 'steel', 'black', '#1d1d1f', '#151515'), V('Blush', 'ivory', 'rose', 'pink', '#6b3a2e', '#f4b6c2')] },
  { b: 'Titan', m: 'Neo Chronograph', ref: '90117KL01', cat: 'chrono', s: 'chrono', p: 8495, mrp: 8995, st: 'leather', size: '44 mm', wr: '50m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 7,
    blurb: 'Smart meets sporty - Titan Neo Chronograph on a rich leather strap.',
    feats: ['Working chronograph', 'Date window', 'Genuine leather strap'], ind: 'stick', date: true,
    v: [V('Blue / Brown', 'blue', 'steel', 'brown', '#ffffff', '#1d4f8c'), V('Black / Black', 'black', 'gun', 'black', '#ff6b1a')] },
  { b: 'Timex', m: 'Expedition Chronograph', ref: 'TW4B04400', cat: 'chrono', s: 'chrono', p: 6995, mrp: 7495, st: 'leather', size: '43 mm', wr: '100m', mv: 'Chronograph Quartz', glass: 'Mineral Glass', pop: 6,
    blurb: 'A rugged outdoor chronograph with Indiglo light and a tough leather strap.',
    feats: ['Chronograph', 'Indiglo night-light', '100m water resistance'], ind: 'arabic',
    v: [V('Black / Brown', 'black', 'steel', 'brown', '#ff6b1a', '#6b4226'), V('Olive / Black', 'olive', 'gun', 'black', '#f5c518', '#4b5a2e')] },
  { b: 'Casio', m: 'Youth AW-49H Ana-Digi', ref: 'AW-49H-1BV', cat: 'sports', s: 'sportdigital', p: 2295, mrp: 2495, st: 'resin', size: '39.5 mm', wr: 'Water Resistant', mv: 'Quartz Analog-Digital', glass: 'Resin Glass', pop: 6,
    blurb: 'Analog hands plus a digital display - the best of both worlds in a light everyday watch.',
    feats: ['Analog + digital display', 'Alarm', 'Stopwatch', '10-year battery'],
    v: [V('Black', 'black', 'resin', 'resin', '#e03131')] },
];
